READMETemplate: logger.Logger Class Reference
logger.Logger Class Reference
Public Member Functions
def __init__ (self, name, bool enable_file_handler=True, bool enable_stream_handler=False, bool enable_syslog_handler=False)
def config (self, Optional[str] log_dir=None, Optional[str] log_filename=None, Optional[Union[str, int]] min_level=None, Optional[int] max_files=None, Optional[int] max_size=None, Optional[str] encoding=None)
def critical (self, msg, *args, **kwargs)
def debug (self, msg, *args, **kwargs)
def error (self, msg, *args, **kwargs)
def format_msg (func)
def info (self, msg, *args, **kwargs)
def logger_put (cls, logger, level, msg, *args, **kwargs)
def logger_run (cls)
def shutdown_logger (cls)
def start_logger (cls, str thread_name="LoggerThread", bool daemon=True, **thread_kwargs)
def warning (self, msg, *args, **kwargs)
Static Public Member Functions
def generate_unique_filename (dir, filename)
def get_creator_class_name ()
def is_valid_encoding (str encoding)
Public Attributes
enable_file_handler
enable_stream_handler
enable_syslog_handler
file_handler
logger_thread
stream_handler
syslog_handler
Static Public Attributes
dictionary log_level_map
logger_queue = queue.Queue()
logger_stop_event = threading.Event()
Private Attributes
_configured
Detailed Description
Definition at line 39 of file logger.py.
Constructor & Destructor Documentation
__init__()
def logger.Logger.__init__ (self, name, bool enable_file_handler = True, bool enable_stream_handler = False, bool enable_syslog_handler = False)
Definition at line 80 of file logger.py.
     def __init__(self, name,
                  enable_file_handler: bool = True,
                  enable_stream_handler: bool = False,
                  enable_syslog_handler: bool = False):
         super().__init__(name)
         # Configuration flag
         self._configured = False
         # Handler flags
         self.enable_file_handler = enable_file_handler
         self.enable_stream_handler = enable_stream_handler
         self.enable_syslog_handler = enable_syslog_handler
         # Handler placeholders
         self.file_handler = None
         self.stream_handler = None
         self.syslog_handler = None
Member Function Documentation
config()
def logger.Logger.config (self, Optional[str] log_dir = None, Optional[str] log_filename = None, Optional[Union[str, int]] min_level = None, Optional[int] max_files = None, Optional[int] max_size = None, Optional[str] encoding = None)
Definition at line 99 of file logger.py.
     def config(self, log_dir: Optional[str] = None,
                      log_filename: Optional[str] = None,
                      min_level: Optional[Union[str, int]] = None,
                      max_files: Optional[int] = None,
                      max_size: Optional[int] = None,
                      encoding: Optional[str] = None):
         if self._configured:
             return
         try:
             log_dir = log_dir or environ.COMMON_LOG_DIR or DefaultLogAttributes.log_dir
             log_filename = log_filename or f"{self.name}.log"
             min_level = min_level or DefaultLogAttributes.min_level
             max_files = max_files or DefaultLogAttributes.max_files
             max_size = max_size or DefaultLogAttributes.max_size
             encoding = encoding or DefaultLogAttributes.encoding
             # Validate configuration attributes
             if not isinstance(max_files, int) or max_files <= 0 or max_files > 50:
                 raise LogWrongAttributeException(f"Wrong max_files attribute: {max_files}")
             if not isinstance(max_size, int) or max_size <= 0 or max_size > 50:
                 raise LogWrongAttributeException(f"Wrong max_size attribute: {max_size}")
             if not isinstance(log_filename, str):
                 raise LogWrongAttributeException(f"Wrong log_filename attribute: {log_filename}")
             if not isinstance(log_dir, str) or not log_dir.strip():
                 raise LogWrongAttributeException(f"Wrong log_dir attribute: {log_dir!r}")
             if isinstance(min_level, str):
                 min_level_up = min_level.upper()
                 if min_level_up not in self.log_level_map:
                     raise LogWrongAttributeException(f"Wrong min_level attribute: {min_level}")
                 log_level = self.log_level_map[min_level_up]
             elif isinstance(min_level, int):
                 if min_level not in self.log_level_map.values():
                     raise LogWrongAttributeException(f"Wrong min_level attribute: {min_level}")
                 log_level = min_level
             else:
                 raise LogWrongAttributeException(f"Wrong min_level attribute: {min_level}")
             if not isinstance(encoding, str) or not self.is_valid_encoding(encoding):
                 raise LogWrongAttributeException(f"Wrong encoding attribute: {encoding}")
             self.setLevel(log_level)
             os.makedirs(log_dir, exist_ok=True)
             # Set Formatter
             file_formatter = logging.Formatter(
                 "DateTime-%(asctime)s|Proc-%(processName)s|Thread-%(threadName)s|"
                 "Mod-%(module)s|Func-%(funcName)s|File-%(pathname)s|Line-%(lineno)d|"
                 "Logger-%(name)s|Level-%(levelname)s: %(message)s"
             )
             stream_formatter = colorlog.ColoredFormatter(
                 "%(log_color)s%(asctime)s|%(processName)s|%(threadName)s|"
                 "%(module)s|%(funcName)s|%(lineno)d|%(levelname)s: %(message)s",
                 log_colors={
                     "DEBUG": "cyan",
                     "INFO": "green",
                     "WARNING": "yellow",
                     "ERROR": "red",
                     "CRITICAL": "red,bg_white",
                 },
                 style='%'
             )
             # FILE HANDLER
             if self.enable_file_handler:
                 self.file_handler = RotatingFileHandler(
                     filename=os.path.join(log_dir, log_filename),
                     maxBytes=1024*1024*max_size,
                     backupCount=max_files,
                     encoding=encoding,
                     delay=True
                 )
                 self.file_handler.setFormatter(file_formatter)
                 self.file_handler.setLevel(log_level)
                 self.addHandler(self.file_handler)
             # STREAM HANDLER
             if self.enable_stream_handler:
                 self.stream_handler = StreamHandler(sys.stdout)
                 self.stream_handler.setFormatter(stream_formatter)
                 self.stream_handler.setLevel(log_level)
                 self.addHandler(self.stream_handler)
             # SYSLOG HANDLER (solo su Unix-like)
             if self.enable_syslog_handler and (sys.platform.startswith("linux") or sys.platform == "darwin"):
                 self.syslog_handler = SysLogHandler(address="/dev/log")
                 self.syslog_handler.setFormatter(file_formatter)
                 self.syslog_handler.setLevel(log_level)
                 self.addHandler(self.syslog_handler)
             self._configured = True
         except Exception as e:
             raise LogConfigurationException(f"Unable to configure logger: {e}")
References logger.Logger._configured, logger.Logger.enable_file_handler, logger.Logger.enable_stream_handler, logger.Logger.enable_syslog_handler, logger.Logger.file_handler, logger.Logger.is_valid_encoding(), logger.Logger.log_level_map, logger.Logger.stream_handler, and logger.Logger.syslog_handler.
critical()
def logger.Logger.critical (self, msg, * args, ** kwargs)
Definition at line 303 of file logger.py.
     def critical(self, msg, *args, **kwargs):
         try:
             self.logger_put(self, "critical", msg, *args, **kwargs)
         except Exception as e:
             raise LogCriticalOperationException(f"Unable to perform critical log operation: {e}")
 Logger.start_logger()
 atexit.register(Logger.shutdown_logger)
References logger.Logger.logger_put().
debug()
def logger.Logger.debug (self, msg, * args, ** kwargs)
Definition at line 274 of file logger.py.
     def debug(self, msg, *args, **kwargs):
         try:
             print("Logger debug message " + str(msg))
             self.logger_put(self, "debug", msg, *args, **kwargs)
         except Exception as e:
             raise LogDebugOperationException(f"Unable to perform debug log operation: {e}")
References logger.Logger.logger_put().
error()
def logger.Logger.error (self, msg, * args, ** kwargs)
Definition at line 296 of file logger.py.
     def error(self, msg, *args, **kwargs):
         try:
             self.logger_put(self, "error", msg, *args, **kwargs)
         except Exception as e:
             raise LogErrorOperationException(f"Unable to perform error log operation: {e}")
References logger.Logger.logger_put().
format_msg()
def logger.Logger.format_msg (func)
Definition at line 53 of file logger.py.
     def format_msg(func):
         @wraps(func)
         def wrapper(self, msg, *args, **kwargs):
             exc_info = None
             if isinstance(msg, BaseException):
                 exc_info = (type(msg), msg, msg.__traceback__)
                 msg = str(msg)
             return func(self, msg, *args, exc_info=exc_info, **kwargs)
         return wrapper
generate_unique_filename()
def logger.Logger.generate_unique_filename (dir, filename) static
Definition at line 72 of file logger.py.
     def generate_unique_filename(dir, filename):
         full_path = os.path.join(dir, filename)
         if not os.path.exists(full_path):
             return full_path
         name, ext = os.path.splitext(filename)
         timestamp = int(time.time())
         return f"{name}_{timestamp}{ext}"
get_creator_class_name()
def logger.Logger.get_creator_class_name () static
Definition at line 64 of file logger.py.
     def get_creator_class_name():
         for frame_info in inspect.stack():
             self_obj = frame_info.frame.f_locals.get('self', None)
             if self_obj and not isinstance(self_obj, Logger):
                 return self_obj.__class__.__name__
         return None
info()
def logger.Logger.info (self, msg, * args, ** kwargs)
Definition at line 282 of file logger.py.
     def info(self, msg, *args, **kwargs):
         try:
             self.logger_put(self, "info", msg, *args, **kwargs)
         except Exception as e:
             raise LogInfoOperationException(f"Unable to perform info log operation: {e}")
References logger.Logger.logger_put().
is_valid_encoding()
def logger.Logger.is_valid_encoding (str encoding) static
Definition at line 266 of file logger.py.
     def is_valid_encoding(encoding: str):
         try:
             codecs.lookup(encoding)
             return True
         except LookupError:
             return False
Referenced by logger.Logger.config().
logger_put()
def logger.Logger.logger_put (cls, logger, level, msg, * args, ** kwargs)
Definition at line 226 of file logger.py.
     def logger_put(cls, logger, level, msg, *args, **kwargs):
         frame_info = inspect.stack()[3]
         record_info = {
             "pathname": frame_info.filename,
             "lineno": frame_info.lineno,
             "funcName": frame_info.function
         }
         cls.logger_queue.put((logger, level, msg, args, kwargs, record_info, kwargs.get("exc_info")))
References logger.Logger.logger_queue.
Referenced by logger.Logger.critical(), logger.Logger.debug(), logger.Logger.error(), logger.Logger.info(), and logger.Logger.warning().
logger_run()
def logger.Logger.logger_run (cls)
Definition at line 195 of file logger.py.
     def logger_run(cls):
         while not cls.logger_stop_event.is_set():
             try:
                 try:
                     log = cls.logger_queue.get(timeout=0.5)
                 except queue.Empty:
                     continue
                 if log is None:
                     break
                 logger, level, msg, args, kwargs, record_info, exc_info = log
                 record = logger.makeRecord(
                     name=logger.name,
                     level=Logger.log_level_map[level.upper()],
                     fn=record_info["pathname"],
                     lno=record_info["lineno"],
                     msg=msg,
                     args=args,
                     exc_info=exc_info,
                     func=record_info["funcName"]
                 )
                 logger.handle(record)
             except Exception as e:
                 print(f"Logger exception: {e}", file=sys.stderr)
References logger.Logger.logger_queue, and logger.Logger.logger_stop_event.
shutdown_logger()
def logger.Logger.shutdown_logger (cls)
Definition at line 249 of file logger.py.
     def shutdown_logger(cls):
         cls.logger_stop_event.set()
         cls.logger_queue.put(None)
         if cls.logger_thread and cls.logger_thread.is_alive():
             cls.logger_thread.join()
         for logger_instance in logging.root.manager.loggerDict.values():
             if isinstance(logger_instance, Logger):
                 for handler in logger_instance.handlers:
                     try:
                         handler.close()
                     except Exception:
                         pass
                     logger_instance.removeHandler(handler)
References logger.Logger.logger_queue, logger.Logger.logger_stop_event, and logger.Logger.logger_thread.
start_logger()
def logger.Logger.start_logger (cls, str thread_name = "LoggerThread", bool daemon = True, ** thread_kwargs)
Definition at line 236 of file logger.py.
     def start_logger(cls, thread_name: str = "LoggerThread", daemon: bool = True, **thread_kwargs):
         if cls.logger_thread is None or not cls.logger_thread.is_alive():
             cls.logger_stop_event.clear()
             cls.logger_thread = threading.Thread(
                 target=cls.logger_run,
                 name=thread_name,
                 daemon=daemon,
                 **thread_kwargs
             )
             cls.logger_thread.start()
         print(f"Logger Thread '{thread_name}' Started")
References logger.Logger.logger_stop_event, and logger.Logger.logger_thread.
warning()
def logger.Logger.warning (self, msg, * args, ** kwargs)
Definition at line 289 of file logger.py.
     def warning(self, msg, *args, **kwargs):
         try:
             self.logger_put(self, "warning", msg, *args, **kwargs)
         except Exception as e:
             raise LogWarningOperationException(f"Unable to perform warning log operation: {e}")
References logger.Logger.logger_put().
Member Data Documentation
_configured
logger.Logger._configured private
Definition at line 84 of file logger.py.
Referenced by logger.Logger.config().
enable_file_handler
logger.Logger.enable_file_handler
Definition at line 87 of file logger.py.
Referenced by logger.Logger.config().
enable_stream_handler
logger.Logger.enable_stream_handler
Definition at line 88 of file logger.py.
Referenced by logger.Logger.config().
enable_syslog_handler
logger.Logger.enable_syslog_handler
Definition at line 89 of file logger.py.
Referenced by logger.Logger.config().
file_handler
logger.Logger.file_handler
Definition at line 92 of file logger.py.
Referenced by logger.Logger.config().
log_level_map
dictionary logger.Logger.log_level_map static
Initial value:
=  {
        "DEBUG": logging.DEBUG,
        "INFO": logging.INFO,
        "WARNING": logging.WARNING,
        "ERROR": logging.ERROR,
        "CRITICAL": logging.CRITICAL
    }
Definition at line 45 of file logger.py.
Referenced by logger.Logger.config().
logger_queue
logger.Logger.logger_queue = queue.Queue() static
Definition at line 40 of file logger.py.
Referenced by logger.Logger.logger_put(), logger.Logger.logger_run(), and logger.Logger.shutdown_logger().
logger_stop_event
logger.Logger.logger_stop_event = threading.Event() static
Definition at line 41 of file logger.py.
Referenced by logger.Logger.logger_run(), logger.Logger.shutdown_logger(), and logger.Logger.start_logger().
logger_thread
logger.Logger.logger_thread
Definition at line 239 of file logger.py.
Referenced by logger.Logger.shutdown_logger(), and logger.Logger.start_logger().
stream_handler
logger.Logger.stream_handler
Definition at line 93 of file logger.py.
Referenced by logger.Logger.config().
syslog_handler
logger.Logger.syslog_handler
Definition at line 94 of file logger.py.
Referenced by logger.Logger.config().
The documentation for this class was generated from the following file:
src/logger.py
⬇️ Download 🐙 View on GitHub
© 2025 Giuseppe Pedone — GitHub