var searchData=
[
  ['obsolescence_20❌_0',['Obsolescence ❌',['../md_Version_2VERSION.html#autotoc_md246',1,'']]],
  ['obsolete_1',['4. Obsolete',['../md_Version_2VERSION.html#autotoc_md243',1,'']]],
  ['of_20changes_2',['🔧 Types of Changes',['../md_Version_2CHANGELOG.html#autotoc_md183',1,'']]],
  ['of_20conduct_3',['of conduct',['../md_README.html#autotoc_md67',1,'4. Code of Conduct'],['../md_CODE__OF__CONDUCT.html',1,'Contributor Covenant Code of Conduct']]],
  ['of_20contents_4',['of contents',['../md_Usage_2DEVELOPMENT__GUIDE.html#autotoc_md108',1,'📓 Table of Contents'],['../md_Usage_2USER__GUIDE.html#autotoc_md142',1,'📓 Table of Contents'],['../md_Version_2API.html#autotoc_md151',1,'📓 Table of Contents'],['../md_Version_2BUG.html#autotoc_md174',1,'📓 Table of Contents'],['../md_Usage_2ADMINISTRATOR__GUIDE.html#autotoc_md83',1,'📓 Table of Contents'],['../md_Version_2CHANGELOG.html#autotoc_md182',1,'📓 Table of Contents'],['../md_Version_2FEATURE.html#autotoc_md189',1,'📓 Table of Contents'],['../md_Version_2FIX.html#autotoc_md201',1,'📓 Table of Contents'],['../md_README.html#autotoc_md25',1,'📓 Table of Contents'],['../md_PROJECT.html#autotoc_md7',1,'📓 Table of Contents'],['../md_Version_2NAMESPACE.html#autotoc_md210',1,'📓 Table of Contents'],['../md_Version_2RELEASE__POLICY.html#autotoc_md222',1,'📓 Table of Contents'],['../md_README.html#autotoc_md57',1,'Table of Contents'],['../md_Version_2VERSION.html#autotoc_md232',1,'Table of Contents']]],
  ['of_20the_20doxygen_20site_5',['Advantages of the Doxygen Site',['../md_PROJECT.html#autotoc_md17',1,'']]],
  ['official_20guides_20📚_6',['Official Guides 📚',['../md_README.html#autotoc_md54',1,'']]],
  ['official_20links_7',['official links',['../md_Version_2FEATURE.html#autotoc_md200',1,'Official Links'],['../md_Version_2FIX.html#autotoc_md209',1,'Official Links'],['../md_Version_2CHANGELOG.html#autotoc_md188',1,'Official Links'],['../md_Version_2BUG.html#autotoc_md181',1,'Official Links'],['../md_Version_2NAMESPACE.html#autotoc_md221',1,'Official Links'],['../md_Version_2API.html#autotoc_md173',1,'Official Links'],['../md_Version_2RELEASE__POLICY.html#autotoc_md231',1,'Official Links'],['../md_Version_2VERSION.html#autotoc_md253',1,'Official Links'],['../md_PROJECT.html#autotoc_md24',1,'Official Links'],['../md_README.html#autotoc_md71',1,'Official Links']]],
  ['on_20gnu_20linux_8',['on gnu linux',['../md_README.html#autotoc_md31',1,'🐧 On GNU/Linux'],['../md_README.html#autotoc_md32',1,'🐧 On GNU/Linux'],['../md_README.html#autotoc_md33',1,'🐧 On GNU/Linux']]],
  ['on_5fincoming_5fmessage_9',['on_incoming_message',['../classbot_1_1Bot.html#aed622df2ae13229f657faecdf83a3909',1,'bot::Bot']]],
  ['on_5foutgoing_5fmessage_10',['on_outgoing_message',['../classbot_1_1Bot.html#a69db2b0d03aa84dc1e3170d0a92b82fb',1,'bot::Bot']]],
  ['one_5fday_5fin_5fseconds_11',['ONE_DAY_IN_SECONDS',['../namespacellm.html#a6e9f5d17d42a13c4393c55994fcefb94',1,'llm']]],
  ['open_20a_20pull_20request_12',['How to Open a Pull Request',['../md_README.html#autotoc_md62',1,'']]],
  ['open_20an_20issue_13',['How to Open an Issue',['../md_README.html#autotoc_md65',1,'']]],
  ['operations_20🧭_14',['User Operations 🧭',['../md_Usage_2USER__GUIDE.html#autotoc_md144',1,'']]],
  ['option_20a_20—_20download_20zip_15',['Option A — Download ZIP',['../md_Usage_2ADMINISTRATOR__GUIDE.html#autotoc_md90',1,'']]],
  ['option_20b_20—_20clone_20repository_16',['Option B — Clone Repository',['../md_Usage_2ADMINISTRATOR__GUIDE.html#autotoc_md91',1,'']]],
  ['optional_17',['optional',['../md_Usage_2ACTORS.html#autotoc_md78',1,'4. CI/CD System (Optional)'],['../md_Usage_2ROLES.html#autotoc_md128',1,'CI/CD Role (Optional)']]],
  ['other_20guides_20📚_18',['other guides 📚',['../namespacemyNamespace.html#autotoc_md121',1,'Other Guides 📚'],['../md_Usage_2USER__GUIDE.html#autotoc_md148',1,'Other Guides 📚'],['../md_Usage_2ADMINISTRATOR__GUIDE.html#autotoc_md105',1,'Other Guides 📚']]],
  ['our_20pledge_19',['Our Pledge',['../md_CODE__OF__CONDUCT.html#autotoc_md1',1,'']]],
  ['our_20responsibilities_20',['Our Responsibilities',['../md_CODE__OF__CONDUCT.html#autotoc_md3',1,'']]],
  ['our_20standards_21',['Our Standards',['../md_CODE__OF__CONDUCT.html#autotoc_md2',1,'']]],
  ['outgoing_5fmessages_22',['outgoing_messages',['../classbot_1_1Bot.html#aa39fcf960e34cbf36063915ba17dc982',1,'bot::Bot']]],
  ['outgoingqueuedmessage_23',['OutgoingQueuedMessage',['../classbot_1_1OutgoingQueuedMessage.html',1,'bot']]],
  ['overview_24',['overview',['../md_Usage_2ADMINISTRATOR__GUIDE.html#autotoc_md84',1,'Administration Overview'],['../md_Usage_2USECASES.html#autotoc_md133',1,'Overview']]],
  ['overview_20👤_25',['User Overview 👤',['../md_Usage_2USER__GUIDE.html#autotoc_md143',1,'']]],
  ['overview_20🧠_26',['Development Overview 🧠',['../md_Usage_2DEVELOPMENT__GUIDE.html#autotoc_md109',1,'']]]
];
