var searchData=
[
  ['obsolescence_20❌_0',['Obsolescence ❌',['../md_Version_2VERSION.html#autotoc_md275',1,'']]],
  ['obsolete_1',['4. Obsolete',['../md_Version_2VERSION.html#autotoc_md272',1,'']]],
  ['of_20changes_2',['🔧 Types of Changes',['../md_Version_2CHANGELOG.html#autotoc_md206',1,'']]],
  ['of_20conduct_3',['of conduct',['../md_README.html#autotoc_md71',1,'4. Code of Conduct'],['../md_CODE__OF__CONDUCT.html',1,'Contributor Covenant Code of Conduct']]],
  ['of_20contents_4',['of contents',['../md_Version_2CHANGELOG.html#autotoc_md205',1,'📓 Table of Contents'],['../md_Usage_2USER__GUIDE.html#autotoc_md163',1,'📓 Table of Contents'],['../md_Version_2RELEASE__POLICY.html#autotoc_md250',1,'📓 Table of Contents'],['../md_Usage_2DEVELOPMENT__GUIDE.html#autotoc_md122',1,'📓 Table of Contents'],['../md_Version_2NAMESPACE.html#autotoc_md238',1,'📓 Table of Contents'],['../md_Version_2API.html#autotoc_md172',1,'📓 Table of Contents'],['../md_Usage_2ADMINISTRATOR__GUIDE.html#autotoc_md87',1,'📓 Table of Contents'],['../md_Version_2BUG.html#autotoc_md197',1,'📓 Table of Contents'],['../md_Version_2FEATURE.html#autotoc_md212',1,'📓 Table of Contents'],['../md_README.html#autotoc_md26',1,'📓 Table of Contents'],['../md_PROJECT.html#autotoc_md7',1,'📓 Table of Contents'],['../md_Version_2FIX.html#autotoc_md229',1,'📓 Table of Contents'],['../md_README.html#autotoc_md61',1,'Table of Contents'],['../md_Version_2VERSION.html#autotoc_md260',1,'Table of Contents']]],
  ['of_20the_20doxygen_20site_5',['Advantages of the Doxygen Site',['../md_PROJECT.html#autotoc_md17',1,'']]],
  ['official_20guides_20📚_6',['Official Guides 📚',['../md_README.html#autotoc_md58',1,'']]],
  ['official_20links_7',['official links',['../md_Version_2VERSION.html#autotoc_md282',1,'Official Links'],['../md_Version_2BUG.html#autotoc_md204',1,'Official Links'],['../md_Version_2API.html#autotoc_md196',1,'Official Links'],['../md_Version_2CHANGELOG.html#autotoc_md211',1,'Official Links'],['../md_Version_2FIX.html#autotoc_md237',1,'Official Links'],['../md_Version_2FEATURE.html#autotoc_md228',1,'Official Links'],['../md_Version_2NAMESPACE.html#autotoc_md249',1,'Official Links'],['../md_Version_2RELEASE__POLICY.html#autotoc_md259',1,'Official Links'],['../md_README.html#autotoc_md75',1,'Official Links'],['../md_PROJECT.html#autotoc_md25',1,'Official Links']]],
  ['on_20gnu_20linux_8',['on gnu linux',['../md_README.html#autotoc_md35',1,'🐧 On GNU/Linux'],['../md_README.html#autotoc_md34',1,'🐧 On GNU/Linux'],['../md_README.html#autotoc_md33',1,'🐧 On GNU/Linux']]],
  ['open_20a_20pull_20request_9',['How to Open a Pull Request',['../md_README.html#autotoc_md66',1,'']]],
  ['open_20an_20issue_10',['How to Open an Issue',['../md_README.html#autotoc_md69',1,'']]],
  ['operations_20🧭_11',['User Operations 🧭',['../md_Usage_2USER__GUIDE.html#autotoc_md165',1,'']]],
  ['option_20a_20—_20download_20zip_12',['Option A — Download ZIP',['../md_Usage_2ADMINISTRATOR__GUIDE.html#autotoc_md99',1,'']]],
  ['option_20b_20—_20clone_20repository_13',['Option B — Clone Repository',['../md_Usage_2ADMINISTRATOR__GUIDE.html#autotoc_md100',1,'']]],
  ['optional_14',['optional',['../md_Usage_2ACTORS.html#autotoc_md82',1,'4. CI/CD System (Optional)'],['../md_Usage_2ROLES.html#autotoc_md142',1,'CI/CD Role (Optional)']]],
  ['other_20guides_20📚_15',['other guides 📚',['../namespacemyNamespace.html#autotoc_md135',1,'Other Guides 📚'],['../md_Usage_2USER__GUIDE.html#autotoc_md169',1,'Other Guides 📚'],['../md_Usage_2ADMINISTRATOR__GUIDE.html#autotoc_md118',1,'Other Guides 📚']]],
  ['our_20pledge_16',['Our Pledge',['../md_CODE__OF__CONDUCT.html#autotoc_md1',1,'']]],
  ['our_20responsibilities_17',['Our Responsibilities',['../md_CODE__OF__CONDUCT.html#autotoc_md3',1,'']]],
  ['our_20standards_18',['Our Standards',['../md_CODE__OF__CONDUCT.html#autotoc_md2',1,'']]],
  ['overview_19',['overview',['../md_Usage_2ADMINISTRATOR__GUIDE.html#autotoc_md89',1,'Administration Overview'],['../md_Usage_2USECASES.html#autotoc_md148',1,'Overview']]],
  ['overview_20👤_20',['User Overview 👤',['../md_Usage_2USER__GUIDE.html#autotoc_md164',1,'']]],
  ['overview_20🧠_21',['Development Overview 🧠',['../md_Usage_2DEVELOPMENT__GUIDE.html#autotoc_md123',1,'']]]
];
