var searchData=
[
  ['a_20—_20download_20zip_0',['Option A — Download ZIP',['../md_Usage_2ADMINISTRATOR__GUIDE.html#autotoc_md84',1,'']]],
  ['a_20bug_1',['Use Case 3 — Report a Bug',['../md_Usage_2USECASES.html#autotoc_md131',1,'']]],
  ['a_20feature_2',['How to use a feature',['../md_Usage_2USER__GUIDE.html#autotoc_md141',1,'']]],
  ['a_20namespace_3a_3',['To add a namespace:',['../namespacecode.html#autotoc_md110',1,'']]],
  ['a_20pull_20request_4',['How to Open a Pull Request',['../md_README.html#autotoc_md56',1,'']]],
  ['a_20version_20includes_5',['🚀 What a Version Includes',['../md_Version_2VERSION.html#autotoc_md227',1,'']]],
  ['about_20new_20features_6',['About New Features',['../md_Version_2FEATURE.html#autotoc_md189',1,'']]],
  ['about_20next_20features_7',['About Next Features',['../md_Version_2FEATURE.html#autotoc_md190',1,'']]],
  ['about_20the_20project_8',['About the Project',['../md_PROJECT.html#autotoc_md8',1,'']]],
  ['about_20the_20project_20🎯_9',['About the Project 🎯',['../md_README.html#autotoc_md26',1,'']]],
  ['access_20as_20administrator_10',['How to access as administrator',['../md_Usage_2ADMINISTRATOR__GUIDE.html#autotoc_md96',1,'']]],
  ['accessibility_11',['🔐 Accessibility',['../md_Version_2API.html#autotoc_md150',1,'']]],
  ['acknowledgements_12',['Acknowledgements',['../md_README.html#autotoc_md67',1,'']]],
  ['actor_20types_13',['Actor Types',['../md_Usage_2ACTORS.html#autotoc_md68',1,'']]],
  ['actors_14',['actors',['../md_Usage_2ACTORS.html',1,'ACTORS'],['../md_Usage_2USECASES.html#autotoc_md128',1,'Actors']]],
  ['actors_20🎮_15',['Usage and Actors 🎮',['../md_README.html#autotoc_md42',1,'']]],
  ['actors_2emd_16',['ACTORS.md',['../ACTORS_8md.html',1,'']]],
  ['add_20a_20namespace_3a_17',['To add a namespace:',['../namespacecode.html#autotoc_md110',1,'']]],
  ['address_20apis_20through_20namespaces_18',['🧩 How To Address APIs through Namespaces',['../md_Version_2NAMESPACE.html#autotoc_md211',1,'']]],
  ['administration_20lifecycle_19',['Administration LifeCycle',['../md_Usage_2ADMINISTRATOR__GUIDE.html#autotoc_md79',1,'']]],
  ['administration_20overview_20',['Administration Overview',['../md_Usage_2ADMINISTRATOR__GUIDE.html#autotoc_md78',1,'']]],
  ['administration_20tasks_21',['Administration Tasks',['../md_Usage_2ADMINISTRATOR__GUIDE.html#autotoc_md80',1,'']]],
  ['administrator_22',['administrator',['../md_Usage_2ACTORS.html#autotoc_md69',1,'1. Administrator'],['../md_Usage_2ADMINISTRATOR__GUIDE.html#autotoc_md96',1,'How to access as administrator']]],
  ['administrator_20role_23',['Administrator Role',['../md_Usage_2ROLES.html#autotoc_md119',1,'']]],
  ['administrator_5fguide_24',['ADMINISTRATOR_GUIDE',['../md_Usage_2ADMINISTRATOR__GUIDE.html',1,'']]],
  ['administrator_5fguide_2emd_25',['ADMINISTRATOR_GUIDE.md',['../ADMINISTRATOR__GUIDE_8md.html',1,'']]],
  ['advantages_26',['Advantages',['../md_PROJECT.html#autotoc_md14',1,'']]],
  ['advantages_20of_20the_20doxygen_20site_27',['Advantages of the Doxygen Site',['../md_PROJECT.html#autotoc_md17',1,'']]],
  ['ai_28',['AI',['../classllm_1_1AI.html',1,'llm']]],
  ['alert_29',['ALERT',['../classexception_1_1ChatbotException_1_1ChatbotExceptionSeverity.html#a930a8846de13b2dfa59d5b4fdce43837',1,'exception::ChatbotException::ChatbotExceptionSeverity']]],
  ['alive_30',['alive',['../classbot_1_1Bot.html#a57e4d6d9c824c063b5fcac4024717e1b',1,'bot::Bot']]],
  ['alpha_20version_31',['1.2 Alpha-Version',['../md_Version_2VERSION.html#autotoc_md234',1,'']]],
  ['also_32',['also',['../md_Version_2CHANGELOG.html#autotoc_md179',1,'See Also'],['../md_Usage_2USECASES.html#autotoc_md133',1,'See Also'],['../md_Version_2API.html#autotoc_md164',1,'See Also'],['../md_Version_2FIX.html#autotoc_md200',1,'See Also'],['../md_Version_2FEATURE.html#autotoc_md191',1,'See Also'],['../md_Version_2BUG.html#autotoc_md172',1,'See Also'],['../md_Version_2RELEASE__POLICY.html#autotoc_md222',1,'See Also'],['../md_Version_2VERSION.html#autotoc_md244',1,'See Also'],['../md_Usage_2ROLES.html#autotoc_md124',1,'See Also'],['../md_Version_2NAMESPACE.html#autotoc_md212',1,'See Also'],['../md_PROJECT.html#autotoc_md21',1,'See Also'],['../md_Usage_2ACTORS.html#autotoc_md74',1,'See Also'],['../md_README.html#autotoc_md62',1,'See Also']]],
  ['an_20issue_33',['How to Open an Issue',['../md_README.html#autotoc_md59',1,'']]],
  ['and_20actors_20🎮_34',['Usage and Actors 🎮',['../md_README.html#autotoc_md42',1,'']]],
  ['and_20contribute_20to_20project_35',['Use Case 2 — Fork and Contribute to Project',['../md_Usage_2USECASES.html#autotoc_md130',1,'']]],
  ['and_20dependencies_36',['Prerequisites and Dependencies',['../md_Usage_2ADMINISTRATOR__GUIDE.html#autotoc_md81',1,'']]],
  ['api_37',['API',['../md_Version_2API.html',1,'']]],
  ['api_20development_20🧠_38',['API Development 🧠',['../md_Usage_2DEVELOPMENT__GUIDE.html#autotoc_md108',1,'']]],
  ['api_20reference_39',['API Reference',['../md_Version_2API.html#autotoc_md153',1,'']]],
  ['api_2emd_40',['API.md',['../API_8md.html',1,'']]],
  ['apis_41',['apis',['../md_Version_2API.html#autotoc_md163',1,'How To Develop APIs'],['../namespacemyNamespace.html#autotoc_md114',1,'How to extend APIs'],['../md_Version_2API.html#autotoc_md162',1,'How To Integrate APIs']]],
  ['apis_20through_20namespaces_42',['🧩 How To Address APIs through Namespaces',['../md_Version_2NAMESPACE.html#autotoc_md211',1,'']]],
  ['app_43',['app',['../namespaceweb__server.html#aec80067c3505e9181d320e27f7022915',1,'web_server']]],
  ['architecture_44',['🚀 Architecture',['../md_PROJECT.html#autotoc_md10',1,'']]],
  ['as_20administrator_45',['How to access as administrator',['../md_Usage_2ADMINISTRATOR__GUIDE.html#autotoc_md96',1,'']]],
  ['ask_5fllm_46',['ask_llm',['../namespacellm.html#a71ee9b464f51902803dbeb01d9396b22',1,'llm']]],
  ['ask_5fllm2_47',['ask_llm2',['../namespacellm.html#a6e1a6c310a84ec855fcaaddab5d6ba19',1,'llm']]],
  ['ask_5fllm3_48',['ask_llm3',['../namespacellm.html#a92bfc5a8d1c0a36739d7d6422dcd00f1',1,'llm']]],
  ['attribution_49',['Attribution',['../md_CODE__OF__CONDUCT.html#autotoc_md6',1,'']]],
  ['authors_20🧑‍💻_50',['Authors 🧑‍💻',['../md_README.html#autotoc_md66',1,'']]],
  ['available_5fsits_51',['available_sits',['../classdatabase_1_1Event.html#a2c0172bc9bf341b6acccfc7686363bfb',1,'database::Event']]]
];
