var searchData=
[
  ['b_20—_20clone_20repository_0',['Option B — Clone Repository',['../md_Usage_2ADMINISTRATOR__GUIDE.html#autotoc_md85',1,'']]],
  ['base_1',['Base',['../namespacedatabase.html#a0a351bcdc86bdc97cd3c88759443bb4a',1,'database']]],
  ['based_20documentation_2',['Markdown-based documentation',['../md_PROJECT.html#autotoc_md11',1,'']]],
  ['based_20site_3',['HTML-based site',['../md_PROJECT.html#autotoc_md15',1,'']]],
  ['beta_20version_4',['1.1 Beta-Version',['../md_Version_2VERSION.html#autotoc_md233',1,'']]],
  ['booking_5',['Booking',['../classdatabase_1_1Booking.html',1,'database']]],
  ['bot_6',['bot',['../namespacebot.html',1,'bot'],['../classbot_1_1Bot.html',1,'bot.Bot']]],
  ['bot_2epy_7',['bot.py',['../bot_8py.html',1,'']]],
  ['bot_5flogger_8',['bot_logger',['../classbot_1_1Bot.html#a4200619881ffd921c83fea1c88ade779',1,'bot::Bot']]],
  ['bot_5fmanager_9',['bot_manager',['../namespacebot.html#a7327be7793178a122ac5c9a6e94ab91a',1,'bot']]],
  ['bot_5fmanager_5flogger_10',['bot_manager_logger',['../classbot_1_1BotManager.html#af7db460e5b74cbed6c0b258752aa68dd',1,'bot::BotManager']]],
  ['bot_5fmanager_5fstop_5fevent_11',['bot_manager_stop_event',['../classbot_1_1BotManager.html#aad03b3d31ea90789a19e02761f425d40',1,'bot::BotManager']]],
  ['bot_5fstop_5fevent_12',['bot_stop_event',['../classbot_1_1Bot.html#a49a3cb244864db94f45e1839a6633b48',1,'bot::Bot']]],
  ['botdeserializationexception_13',['BotDeserializationException',['../classbot_1_1BotDeserializationException.html',1,'bot']]],
  ['botexception_14',['BotException',['../classbot_1_1BotException.html',1,'bot']]],
  ['bothealthcheckexception_15',['BotHealthCheckException',['../classbot_1_1BotHealthCheckException.html',1,'bot']]],
  ['botinitializationexception_16',['BotInitializationException',['../classbot_1_1BotInitializationException.html',1,'bot']]],
  ['botmanager_17',['BotManager',['../classbot_1_1BotManager.html',1,'bot']]],
  ['botmanageralivecheckexception_18',['BotManagerAliveCheckException',['../classbot_1_1BotManagerAliveCheckException.html',1,'bot']]],
  ['botmanagerbotexception_19',['BotManagerBotException',['../classbot_1_1BotManagerBotException.html',1,'bot']]],
  ['botmanagerexception_20',['BotManagerException',['../classbot_1_1BotManagerException.html',1,'bot']]],
  ['botmanagerstartexception_21',['BotManagerStartException',['../classbot_1_1BotManagerStartException.html',1,'bot']]],
  ['botmanagerstopexception_22',['BotManagerStopException',['../classbot_1_1BotManagerStopException.html',1,'bot']]],
  ['botmanagerthreadexception_23',['BotManagerThreadException',['../classbot_1_1BotManagerThreadException.html',1,'bot']]],
  ['botmessageexception_24',['BotMessageException',['../classbot_1_1BotMessageException.html',1,'bot']]],
  ['botmessagequeueemptyexception_25',['BotMessageQueueEmptyException',['../classbot_1_1BotMessageQueueEmptyException.html',1,'bot']]],
  ['botmessagequeueexception_26',['BotMessageQueueException',['../classbot_1_1BotMessageQueueException.html',1,'bot']]],
  ['botmessagequeuefullexception_27',['BotMessageQueueFullException',['../classbot_1_1BotMessageQueueFullException.html',1,'bot']]],
  ['botmessagequeuelockexception_28',['BotMessageQueueLockException',['../classbot_1_1BotMessageQueueLockException.html',1,'bot']]],
  ['botqueuedmessageexception_29',['BotQueuedMessageException',['../classbot_1_1BotQueuedMessageException.html',1,'bot']]],
  ['botqueuedmessageinvalidexception_30',['BotQueuedMessageInvalidException',['../classbot_1_1BotQueuedMessageInvalidException.html',1,'bot']]],
  ['botqueuedmessageresultexception_31',['BotQueuedMessageResultException',['../classbot_1_1BotQueuedMessageResultException.html',1,'bot']]],
  ['botqueueexception_32',['BotQueueException',['../classbot_1_1BotQueueException.html',1,'bot']]],
  ['botreceivemessageexception_33',['BotReceiveMessageException',['../classbot_1_1BotReceiveMessageException.html',1,'bot']]],
  ['bots_5finfo_5fjson_34',['bots_info_json',['../classbot_1_1BotManager.html#a3560d2d01d94db79fee6a4d948e5c845',1,'bot::BotManager']]],
  ['bots_5finfo_5fstr_35',['bots_info_str',['../classbot_1_1BotManager.html#a68fa845b02188649c895b1c691d0c786',1,'bot::BotManager']]],
  ['botsendmessageexception_36',['BotSendMessageException',['../classbot_1_1BotSendMessageException.html',1,'bot']]],
  ['botserializationexception_37',['BotSerializationException',['../classbot_1_1BotSerializationException.html',1,'bot']]],
  ['botstartexception_38',['BotStartException',['../classbot_1_1BotStartException.html',1,'bot']]],
  ['botstartthreadexception_39',['BotStartThreadException',['../classbot_1_1BotStartThreadException.html',1,'bot']]],
  ['botstopexception_40',['BotStopException',['../classbot_1_1BotStopException.html',1,'bot']]],
  ['botstopthreadexception_41',['BotStopThreadException',['../classbot_1_1BotStopThreadException.html',1,'bot']]],
  ['botthreadexception_42',['BotThreadException',['../classbot_1_1BotThreadException.html',1,'bot']]],
  ['bug_43',['bug',['../md_Version_2BUG.html',1,'BUG'],['../md_Usage_2USECASES.html#autotoc_md131',1,'Use Case 3 — Report a Bug']]],
  ['bug_20fix_20tracking_20🔥_44',['Bug &amp; Fix Tracking 🔥',['../md_README.html#autotoc_md45',1,'']]],
  ['bug_20tracer_45',['🧾 Bug Tracer',['../md_Version_2BUG.html#autotoc_md171',1,'']]],
  ['bug_2emd_46',['BUG.md',['../BUG_8md.html',1,'']]],
  ['bugs_20🐛_47',['Bugs 🐛',['../md_Version_2VERSION.html#autotoc_md241',1,'']]],
  ['build_48',['build',['../md_README.html#autotoc_md36',1,'🛠️ Build'],['../md_Usage_2ADMINISTRATOR__GUIDE.html#autotoc_md86',1,'Build']]],
  ['build_20the_20project_20template_20build_49',['How to build the project (Template build)',['../namespacemyNamespace.html#autotoc_md112',1,'']]],
  ['by_50',['🎮 Used by',['../md_Version_2API.html#autotoc_md147',1,'']]]
];
