var searchData=
[
  ['readme_0',['README',['../md_README.html',1,'']]],
  ['readme_2emd_1',['README.md',['../README_8md.html',1,'']]],
  ['receive_5fmessage_2',['receive_message',['../classbot_1_1Bot.html#af288ded3335d70c2c4e83f0b32a9d1d9',1,'bot::Bot']]],
  ['receive_5fmessage_5ffrom_5fbot_3',['receive_message_from_bot',['../classbot_1_1BotManager.html#afcf8120800e601f205fe2ad2a2436efa',1,'bot::BotManager']]],
  ['reference_4',['reference',['../md_Version_2API.html#autotoc_md159',1,'API Reference'],['../md_Version_2FEATURE.html#autotoc_md190',1,'Feature Reference'],['../md_Version_2NAMESPACE.html#autotoc_md211',1,'Namespace Reference']]],
  ['registration_5',['🗂️ Version Registration',['../md_Version_2VERSION.html#autotoc_md236',1,'']]],
  ['release_6',['release',['../md_Version_2VERSION.html#autotoc_md238',1,'1. Pre-Release'],['../md_Version_2VERSION.html#autotoc_md241',1,'2. Release']]],
  ['release_20policy_20📜_7',['release policy 📜',['../md_Version_2VERSION.html#autotoc_md249',1,'Release Policy 📜'],['../md_README.html#autotoc_md50',1,'Release Policy 📜']]],
  ['release_20policy_20standard_8',['Release Policy Standard',['../md_Version_2RELEASE__POLICY.html#autotoc_md223',1,'']]],
  ['release_5fpolicy_9',['RELEASE_POLICY',['../md_Version_2RELEASE__POLICY.html',1,'']]],
  ['release_5fpolicy_2emd_10',['RELEASE_POLICY.md',['../RELEASE__POLICY_8md.html',1,'']]],
  ['releases_20⭐_11',['Releases ⭐',['../md_README.html#autotoc_md49',1,'']]],
  ['report_20a_20bug_12',['Use Case 3 — Report a Bug',['../md_Usage_2USECASES.html#autotoc_md137',1,'']]],
  ['repository_13',['Option B — Clone Repository',['../md_Usage_2ADMINISTRATOR__GUIDE.html#autotoc_md91',1,'']]],
  ['request_14',['How to Open a Pull Request',['../md_README.html#autotoc_md62',1,'']]],
  ['request_20guidelines_15',['Pull Request Guidelines',['../md_README.html#autotoc_md63',1,'']]],
  ['requests_16',['2. Pull Requests',['../md_README.html#autotoc_md61',1,'']]],
  ['responsibilities_17',['responsibilities',['../md_Usage_2DEVELOPMENT__GUIDE.html#autotoc_md113',1,'Developer responsibilities'],['../md_CODE__OF__CONDUCT.html#autotoc_md3',1,'Our Responsibilities']]],
  ['restart_20the_20system_18',['How to restart the system',['../md_Usage_2ADMINISTRATOR__GUIDE.html#autotoc_md103',1,'']]],
  ['result_19',['result',['../classbot_1_1QueuedMessage.html#a84c56594de1f61a83fc05bd5b159d668',1,'bot::QueuedMessage']]],
  ['role_20',['role',['../md_Usage_2ROLES.html#autotoc_md125',1,'Administrator Role'],['../md_Usage_2ROLES.html#autotoc_md126',1,'Developer Role'],['../md_Usage_2ROLES.html#autotoc_md127',1,'User Role']]],
  ['role_20optional_21',['CI/CD Role (Optional)',['../md_Usage_2ROLES.html#autotoc_md128',1,'']]],
  ['role_20permissions_22',['Role Permissions',['../md_Usage_2ROLES.html#autotoc_md129',1,'']]],
  ['roles_23',['ROLES',['../md_Usage_2ROLES.html',1,'']]],
  ['roles_20description_24',['Roles Description',['../md_Usage_2ROLES.html#autotoc_md124',1,'']]],
  ['roles_2emd_25',['ROLES.md',['../ROLES_8md.html',1,'']]],
  ['rules_26',['rules',['../md_README.html#autotoc_md58',1,'General Contribution Rules'],['../md_Version_2RELEASE__POLICY.html#autotoc_md227',1,'Versioning Grammar Rules'],['../md_Version_2RELEASE__POLICY.html#autotoc_md226',1,'Versioning Precedence Rules']]],
  ['rules_20📘_27',['Versioning Rules 📘',['../md_Version_2RELEASE__POLICY.html#autotoc_md225',1,'']]],
  ['run_28',['run',['../md_README.html#autotoc_md43',1,'🚀 Run'],['../classbot_1_1BotManager.html#ad241d4a98df64724c4c6901a8fcc2c05',1,'bot.BotManager.run(self)']]],
  ['run_5fcycle_5ftime_29',['run_cycle_time',['../classbot_1_1BotManager.html#a1cb262014e9b8ff0bf1fe404ed92891d',1,'bot::BotManager']]],
  ['run_5fthread_30',['run_thread',['../classbot_1_1BotManager.html#a46135d2f900f134d460674eba7c361de',1,'bot::BotManager']]]
];
