var searchData=
[
  ['_3abookmark_3a_20apis_20namespaces_0',[':bookmark: APIs &amp; Namespaces',['../index.html#autotoc_md47',1,'']]],
  ['_3abooks_3a_20official_20guides_1',[':books: Official Guides',['../index.html#autotoc_md57',1,'']]],
  ['_3abuilding_5fconstruction_3a_20architecture_2',[':building_construction: Architecture',['../md_PROJECT.html#autotoc_md13',1,'']]],
  ['_3acomputer_3a_20prerequisites_3',[':computer: Prerequisites',['../index.html#autotoc_md37',1,'']]],
  ['_3acomputer_3a_20teck_20stack_4',[':computer: Teck Stack',['../md_PROJECT.html#autotoc_md16',1,'']]],
  ['_3adart_3a_20project_5',[':dart: Project',['../index.html#autotoc_md29',1,'']]],
  ['_3aearth_5fafrica_3a_20deployment_6',[':earth_africa: Deployment',['../index.html#autotoc_md44',1,'']]],
  ['_3afile_5ffolder_3a_20directory_20tree_7',[':file_folder: Directory Tree',['../md_PROJECT.html#autotoc_md18',1,'']]],
  ['_3afire_3a_20bug_20fix_20tracking_8',[':fire: Bug &amp; Fix Tracking',['../index.html#autotoc_md50',1,'']]],
  ['_3aframed_5fpicture_3a_20screenshots_9',[':framed_picture: Screenshots',['../md_Usage_2USECASES.html#autotoc_md129',1,'']]],
  ['_3agear_3a_20change_20log_10',[':gear: Change Log',['../index.html#autotoc_md51',1,'']]],
  ['_3agear_3a_20configuration_11',[':gear: Configuration',['../index.html#autotoc_md40',1,'']]],
  ['_3agrey_5fquestion_3a_20faq_12',[':grey_question: faq',['../index.html#autotoc_md72',1,':grey_question: FAQ'],['../md_PROJECT.html#autotoc_md25',1,':grey_question: FAQ']]],
  ['_3ahammer_5fand_5fwrench_3a_20build_13',[':hammer_and_wrench: Build',['../index.html#autotoc_md43',1,'']]],
  ['_3ahammer_5fand_5fwrench_3a_20how_20to_14',[':hammer_and_wrench: How To',['../index.html#autotoc_md55',1,'']]],
  ['_3alabel_3a_20available_20versions_15',[':label: Available versions',['../index.html#autotoc_md33',1,'']]],
  ['_3alabel_3a_20versions_20features_16',[':label: Versions &amp; Features',['../index.html#autotoc_md32',1,'']]],
  ['_3anotebook_5fwith_5fdecorative_5fcover_3a_20table_20of_20contents_17',[':notebook_with_decorative_cover: table of contents',['../md_PROJECT.html#autotoc_md9',1,':notebook_with_decorative_cover: Table of Contents'],['../md_Version_2VERSION.html#autotoc_md298',1,':notebook_with_decorative_cover: Table of Contents'],['../md_Version_2RELEASE__POLICY.html#autotoc_md287',1,':notebook_with_decorative_cover: Table of Contents'],['../md_Version_2NAMESPACE.html#autotoc_md267',1,':notebook_with_decorative_cover: Table of Contents'],['../md_Usage_2ACTORS.html#autotoc_md82',1,':notebook_with_decorative_cover: Table of Contents'],['../md_Usage_2ADMINISTRATOR__GUIDE.html#autotoc_md95',1,':notebook_with_decorative_cover: Table of Contents'],['../md_Version_2FIX.html#autotoc_md258',1,':notebook_with_decorative_cover: Table of Contents'],['../md_Usage_2DEVELOPMENT__GUIDE.html#autotoc_md108',1,':notebook_with_decorative_cover: Table of Contents'],['../md_Usage_2ROLES.html#autotoc_md121',1,':notebook_with_decorative_cover: Table of Contents'],['../md_Version_2FEATURE.html#autotoc_md225',1,':notebook_with_decorative_cover: Table of Contents'],['../md_Version_2CHANGELOG.html#autotoc_md218',1,':notebook_with_decorative_cover: Table of Contents'],['../md_Usage_2USER__GUIDE.html#autotoc_md135',1,':notebook_with_decorative_cover: Table of Contents'],['../md_Version_2API.html#autotoc_md143',1,':notebook_with_decorative_cover: Table of Contents'],['../md_Version_2BUG.html#autotoc_md209',1,':notebook_with_decorative_cover: Table of Contents'],['../index.html#autotoc_md27',1,':notebook_with_decorative_cover: Table of Contents']]],
  ['_3apackage_3a_20dependencies_18',[':package: Dependencies',['../index.html#autotoc_md38',1,'']]],
  ['_3apackage_3a_20namespaces_19',[':package: Namespaces',['../index.html#autotoc_md49',1,'']]],
  ['_3apaperclip_3a_20exit_20',[':paperclip: Exit',['../md_Version_2API.html#autotoc_md164',1,'']]],
  ['_3apaperclip_3a_20start_21',[':paperclip: Start',['../md_Version_2API.html#autotoc_md151',1,'']]],
  ['_3apaperclip_3a_20terminate_22',[':paperclip: Terminate',['../md_Version_2API.html#autotoc_md177',1,'']]],
  ['_3apaperclip_3a_20wait_23',[':paperclip: Wait',['../md_Version_2API.html#autotoc_md189',1,'']]],
  ['_3aphone_3a_20contact_20us_24',[':phone: contact us',['../md_CONTACT__US.html#autotoc_md7',1,':phone: Contact us'],['../md_PROJECT.html#autotoc_md26',1,':phone: Contact us'],['../index.html#autotoc_md73',1,':phone: Contact us']]],
  ['_3apill_3a_20usage_20examples_25',[':pill: usage examples',['../md_Version_2FEATURE.html#autotoc_md244',1,':pill: Usage Examples'],['../md_Version_2FEATURE.html#autotoc_md238',1,':pill: Usage Examples'],['../md_Version_2FEATURE.html#autotoc_md232',1,':pill: Usage Examples']]],
  ['_3arocket_3a_20getting_20started_26',[':rocket: Getting Started',['../index.html#autotoc_md36',1,'']]],
  ['_3arocket_3a_20run_27',[':rocket: Run',['../index.html#autotoc_md42',1,'']]],
  ['_3ascroll_3a_20change_20logging_20register_28',[':scroll: change logging register',['../md_Usage_2ROLES.html#autotoc_md120',1,':scroll: Change Logging Register'],['../md_Usage_2DEVELOPMENT__GUIDE.html#autotoc_md107',1,':scroll: Change Logging Register'],['../md_Usage_2USER__GUIDE.html#autotoc_md134',1,':scroll: Change Logging Register'],['../md_Usage_2ADMINISTRATOR__GUIDE.html#autotoc_md94',1,':scroll: Change Logging Register'],['../md_Usage_2ACTORS.html#autotoc_md81',1,':scroll: Change Logging Register']]],
  ['_3ascroll_3a_20licenses_29',[':scroll: licenses',['../index.html#autotoc_md59',1,':scroll: Licenses'],['../md_PROJECT.html#autotoc_md21',1,':scroll: Licenses']]],
  ['_3ascroll_3a_20release_20policy_30',[':scroll: Release Policy',['../index.html#autotoc_md58',1,'']]],
  ['_3asoccer_3a_20goal_31',[':soccer: Goal',['../md_PROJECT.html#autotoc_md11',1,'']]],
  ['_3astar_3a_20available_20features_32',[':star: Available features',['../index.html#autotoc_md34',1,'']]],
  ['_3astar_3a_20command_33',[':star: Command',['../md_Version_2NAMESPACE.html#autotoc_md275',1,'']]],
  ['_3astar_3a_20control_34',[':star: Control',['../md_Version_2NAMESPACE.html#autotoc_md274',1,'']]],
  ['_3astar_3a_20feature_200_35',[':star: Feature 0',['../md_Version_2FEATURE.html#autotoc_md231',1,'']]],
  ['_3astar_3a_20feature_201_36',[':star: Feature 1',['../md_Version_2FEATURE.html#autotoc_md237',1,'']]],
  ['_3astar_3a_20feature_202_37',[':star: Feature 2',['../md_Version_2FEATURE.html#autotoc_md243',1,'']]],
  ['_3astar_3a_20installation_38',[':star: Installation',['../index.html#autotoc_md39',1,'']]],
  ['_3astar_3a_20process_39',[':star: Process',['../md_Version_2NAMESPACE.html#autotoc_md277',1,'']]],
  ['_3avideo_5fgame_3a_20usage_20actors_40',[':video_game: Usage &amp; Actors',['../index.html#autotoc_md30',1,'']]],
  ['_3awarning_3a_20issue_41',[':warning: Issue',['../index.html#autotoc_md66',1,'']]],
  ['_3awarning_3a_20requirements_42',[':warning: requirements',['../md_Version_2FEATURE.html#autotoc_md246',1,':warning: Requirements'],['../md_Version_2FEATURE.html#autotoc_md240',1,':warning: Requirements'],['../md_Version_2FEATURE.html#autotoc_md234',1,':warning: Requirements']]],
  ['_3awave_3a_20contributing_43',[':wave: Contributing',['../index.html#autotoc_md61',1,'']]],
  ['_3awhite_5fcheck_5fmark_3a_20tests_44',[':white_check_mark: Tests',['../index.html#autotoc_md41',1,'']]],
  ['_3ax_3a_20uninstall_45',[':x: Uninstall',['../index.html#autotoc_md45',1,'']]]
];
