var searchData=
[
  ['reference_0',['reference',['../md_readme_2Version_2API.html#autotoc_md149',1,'API Reference'],['../md_readme_2Version_2FEATURE.html#autotoc_md230',1,'Feature Reference'],['../md_readme_2Version_2NAMESPACE.html#autotoc_md273',1,'Namespace Reference']]],
  ['register_1',['register',['../md_readme_2Usage_2ACTORS.html#autotoc_md81',1,':scroll: Change Logging Register'],['../md_readme_2Usage_2USER__GUIDE.html#autotoc_md134',1,':scroll: Change Logging Register'],['../md_readme_2Usage_2ROLES.html#autotoc_md120',1,':scroll: Change Logging Register'],['../md_readme_2Usage_2ADMINISTRATOR__GUIDE.html#autotoc_md94',1,':scroll: Change Logging Register'],['../md_readme_2Usage_2DEVELOPMENT__GUIDE.html#autotoc_md107',1,':scroll: Change Logging Register']]],
  ['release_2',['release',['../md_readme_2Version_2VERSION.html#autotoc_md301',1,'Pre-Release'],['../md_readme_2Version_2VERSION.html#autotoc_md304',1,'Release']]],
  ['release_20policy_3',['release policy',['../md_readme_2Version_2VERSION.html#autotoc_md312',1,'Release Policy'],['../md_readme_2Version_2RELEASE__POLICY.html#autotoc_md288',1,'Release Policy']]],
  ['release_20policy_20📜_4',['Release Policy 📜',['../index.html#autotoc_md58',1,'']]],
  ['release_20policy_20brief_20description_5',['release policy brief description',['../md_readme_2Usage_2ROLES.html#autotoc_md122',1,'Release Policy Brief Description'],['../md_readme_2Usage_2USER__GUIDE.html#autotoc_md136',1,'Release Policy Brief Description'],['../md_readme_2Usage_2DEVELOPMENT__GUIDE.html#autotoc_md109',1,'Release Policy Brief Description'],['../md_readme_2Usage_2ACTORS.html#autotoc_md83',1,'Release Policy Brief Description'],['../md_readme_2Usage_2ADMINISTRATOR__GUIDE.html#autotoc_md96',1,'Release Policy Brief Description']]],
  ['release_20policy_20standard_6',['Release Policy Standard',['../md_readme_2Version_2RELEASE__POLICY.html#autotoc_md289',1,'']]],
  ['release_5fpolicy_7',['RELEASE_POLICY',['../md_readme_2Version_2RELEASE__POLICY.html',1,'']]],
  ['removed_8',['removed',['../md_readme_2Usage_2DEVELOPMENT__GUIDE.html#autotoc_md106',1,'Removed'],['../md_readme_2Usage_2ROLES.html#autotoc_md119',1,'Removed'],['../md_readme_2Usage_2ADMINISTRATOR__GUIDE.html#autotoc_md93',1,'Removed'],['../md_readme_2Usage_2ACTORS.html#autotoc_md80',1,'Removed'],['../md_readme_2Usage_2USER__GUIDE.html#autotoc_md133',1,'Removed']]],
  ['request_9',['request',['../index.html#autotoc_md65',1,'How to make a pull request'],['../index.html#autotoc_md64',1,'Pull Request']]],
  ['requirements_10',['requirements',['../md_readme_2Version_2FEATURE.html#autotoc_md246',1,':warning: Requirements'],['../md_readme_2Version_2FEATURE.html#autotoc_md240',1,':warning: Requirements'],['../md_readme_2Version_2FEATURE.html#autotoc_md234',1,':warning: Requirements']]],
  ['responsibilities_11',['Our Responsibilities',['../md_readme_2CODE__OF__CONDUCT.html#autotoc_md3',1,'']]],
  ['roles_12',['roles',['../md_readme_2Version_2FEATURE.html#autotoc_md247',1,'Actors and Roles'],['../md_readme_2Version_2FEATURE.html#autotoc_md241',1,'Actors and Roles'],['../md_readme_2Version_2FEATURE.html#autotoc_md235',1,'Actors and Roles']]],
  ['rules_13',['rules',['../md_readme_2Version_2RELEASE__POLICY.html#autotoc_md293',1,'Versioning Grammar Rules'],['../md_readme_2Usage_2ADMINISTRATOR__GUIDE.html#autotoc_md101',1,'Versioning Grammar Rules'],['../md_readme_2Usage_2USER__GUIDE.html#autotoc_md141',1,'Versioning Grammar Rules'],['../md_readme_2Usage_2DEVELOPMENT__GUIDE.html#autotoc_md114',1,'Versioning Grammar Rules'],['../md_readme_2Usage_2ACTORS.html#autotoc_md88',1,'Versioning Grammar Rules'],['../md_readme_2Usage_2ROLES.html#autotoc_md127',1,'Versioning Grammar Rules'],['../md_readme_2Usage_2ADMINISTRATOR__GUIDE.html#autotoc_md100',1,'Versioning Precedence Rules'],['../md_readme_2Version_2RELEASE__POLICY.html#autotoc_md292',1,'Versioning Precedence Rules'],['../md_readme_2Usage_2DEVELOPMENT__GUIDE.html#autotoc_md113',1,'Versioning Precedence Rules'],['../md_readme_2Usage_2ROLES.html#autotoc_md126',1,'Versioning Precedence Rules'],['../md_readme_2Usage_2ACTORS.html#autotoc_md87',1,'Versioning Precedence Rules'],['../md_readme_2Usage_2USER__GUIDE.html#autotoc_md140',1,'Versioning Precedence Rules'],['../md_readme_2Usage_2ROLES.html#autotoc_md125',1,'Versioning Rules'],['../md_readme_2Usage_2USER__GUIDE.html#autotoc_md139',1,'Versioning Rules'],['../md_readme_2Version_2RELEASE__POLICY.html#autotoc_md291',1,'Versioning Rules'],['../md_readme_2Usage_2DEVELOPMENT__GUIDE.html#autotoc_md112',1,'Versioning Rules'],['../md_readme_2Usage_2ADMINISTRATOR__GUIDE.html#autotoc_md99',1,'Versioning Rules'],['../md_readme_2Usage_2ACTORS.html#autotoc_md86',1,'Versioning Rules']]],
  ['run_14',['🚀 Run',['../index.html#autotoc_md42',1,'']]]
];
