var searchData=
[
  ['readme_0',['README',['../md_README.html',1,'']]],
  ['readme_2emd_1',['README.md',['../README_8md.html',1,'']]],
  ['reference_2',['reference',['../md_Version_2API.html#autotoc_md180',1,'API Reference'],['../md_Version_2FEATURE.html#autotoc_md213',1,'Feature Reference'],['../md_Version_2NAMESPACE.html#autotoc_md239',1,'Namespace Reference']]],
  ['registration_3',['🗂️ Version Registration',['../md_Version_2VERSION.html#autotoc_md264',1,'']]],
  ['release_4',['release',['../md_Version_2VERSION.html#autotoc_md267',1,'1. Pre-Release'],['../md_Version_2VERSION.html#autotoc_md270',1,'2. Release']]],
  ['release_20policy_20📜_5',['release policy 📜',['../md_Version_2VERSION.html#autotoc_md278',1,'Release Policy 📜'],['../md_README.html#autotoc_md54',1,'Release Policy 📜']]],
  ['release_20policy_20standard_6',['Release Policy Standard',['../md_Version_2RELEASE__POLICY.html#autotoc_md251',1,'']]],
  ['release_5fpolicy_7',['RELEASE_POLICY',['../md_Version_2RELEASE__POLICY.html',1,'']]],
  ['release_5fpolicy_2emd_8',['RELEASE_POLICY.md',['../RELEASE__POLICY_8md.html',1,'']]],
  ['releases_20⭐_9',['Releases ⭐',['../md_README.html#autotoc_md53',1,'']]],
  ['report_20a_20bug_10',['Use Case 3 — Report a Bug',['../md_Usage_2USECASES.html#autotoc_md156',1,'']]],
  ['repository_11',['Option B — Clone Repository',['../md_Usage_2ADMINISTRATOR__GUIDE.html#autotoc_md100',1,'']]],
  ['request_12',['How to Open a Pull Request',['../md_README.html#autotoc_md66',1,'']]],
  ['request_20guidelines_13',['Pull Request Guidelines',['../md_README.html#autotoc_md67',1,'']]],
  ['requests_14',['2. Pull Requests',['../md_README.html#autotoc_md65',1,'']]],
  ['responsibilities_15',['responsibilities',['../md_Usage_2DEVELOPMENT__GUIDE.html#autotoc_md127',1,'Developer responsibilities'],['../md_CODE__OF__CONDUCT.html#autotoc_md3',1,'Our Responsibilities']]],
  ['restart_20the_20system_16',['How to restart the system',['../md_Usage_2ADMINISTRATOR__GUIDE.html#autotoc_md116',1,'']]],
  ['role_17',['role',['../md_Usage_2ROLES.html#autotoc_md139',1,'Administrator Role'],['../md_Usage_2ROLES.html#autotoc_md140',1,'Developer Role'],['../md_Usage_2ROLES.html#autotoc_md141',1,'User Role']]],
  ['role_20optional_18',['CI/CD Role (Optional)',['../md_Usage_2ROLES.html#autotoc_md142',1,'']]],
  ['role_20permissions_19',['Role Permissions',['../md_Usage_2ROLES.html#autotoc_md144',1,'']]],
  ['roles_20',['ROLES',['../md_Usage_2ROLES.html',1,'']]],
  ['roles_20description_21',['Roles Description',['../md_Usage_2ROLES.html#autotoc_md138',1,'']]],
  ['roles_2emd_22',['ROLES.md',['../ROLES_8md.html',1,'']]],
  ['rules_23',['rules',['../md_README.html#autotoc_md62',1,'General Contribution Rules'],['../md_Version_2RELEASE__POLICY.html#autotoc_md255',1,'Versioning Grammar Rules'],['../md_Version_2RELEASE__POLICY.html#autotoc_md254',1,'Versioning Precedence Rules']]],
  ['rules_20📘_24',['Versioning Rules 📘',['../md_Version_2RELEASE__POLICY.html#autotoc_md253',1,'']]],
  ['run_25',['🚀 Run',['../md_README.html#autotoc_md47',1,'']]]
];
