var searchData=
[
  ['a_20—_20download_20zip_0',['Option A — Download ZIP',['../md_Usage_2ADMINISTRATOR__GUIDE.html#autotoc_md94',1,'']]],
  ['a_20bug_1',['Use Case 3 — Report a Bug',['../md_Usage_2USECASES.html#autotoc_md141',1,'']]],
  ['a_20feature_2',['How to use a feature',['../md_Usage_2USER__GUIDE.html#autotoc_md151',1,'']]],
  ['a_20namespace_3a_3',['To add a namespace:',['../namespacecode.html#autotoc_md120',1,'']]],
  ['a_20pull_20request_4',['How to Open a Pull Request',['../md_README.html#autotoc_md66',1,'']]],
  ['a_20version_20includes_5',['🚀 What a Version Includes',['../md_Version_2VERSION.html#autotoc_md244',1,'']]],
  ['about_20new_20features_6',['About New Features',['../md_Version_2FEATURE.html#autotoc_md204',1,'']]],
  ['about_20next_20features_7',['About Next Features',['../md_Version_2FEATURE.html#autotoc_md206',1,'']]],
  ['about_20the_20project_8',['About the Project',['../md_PROJECT.html#autotoc_md8',1,'']]],
  ['about_20the_20project_20🎯_9',['About the Project 🎯',['../md_README.html#autotoc_md27',1,'']]],
  ['access_20as_20administrator_10',['How to access as administrator',['../md_Usage_2ADMINISTRATOR__GUIDE.html#autotoc_md106',1,'']]],
  ['accessibility_11',['🔐 Accessibility',['../md_Version_2API.html#autotoc_md160',1,'']]],
  ['acknowledgements_12',['Acknowledgements',['../md_README.html#autotoc_md77',1,'']]],
  ['actor_20types_13',['Actor Types',['../md_Usage_2ACTORS.html#autotoc_md78',1,'']]],
  ['actors_14',['actors',['../md_Usage_2ACTORS.html',1,'ACTORS'],['../md_Usage_2USECASES.html#autotoc_md138',1,'Actors']]],
  ['actors_20🎮_15',['Usage and Actors 🎮',['../md_README.html#autotoc_md52',1,'']]],
  ['actors_2emd_16',['ACTORS.md',['../ACTORS_8md.html',1,'']]],
  ['add_20a_20namespace_3a_17',['To add a namespace:',['../namespacecode.html#autotoc_md120',1,'']]],
  ['address_20apis_20through_20namespaces_18',['🧩 How To Address APIs through Namespaces',['../md_Version_2NAMESPACE.html#autotoc_md228',1,'']]],
  ['administration_20lifecycle_19',['Administration LifeCycle',['../md_Usage_2ADMINISTRATOR__GUIDE.html#autotoc_md89',1,'']]],
  ['administration_20overview_20',['Administration Overview',['../md_Usage_2ADMINISTRATOR__GUIDE.html#autotoc_md88',1,'']]],
  ['administration_20tasks_21',['Administration Tasks',['../md_Usage_2ADMINISTRATOR__GUIDE.html#autotoc_md90',1,'']]],
  ['administrator_22',['administrator',['../md_Usage_2ACTORS.html#autotoc_md79',1,'1. Administrator'],['../md_Usage_2ADMINISTRATOR__GUIDE.html#autotoc_md106',1,'How to access as administrator']]],
  ['administrator_20role_23',['Administrator Role',['../md_Usage_2ROLES.html#autotoc_md129',1,'']]],
  ['administrator_5fguide_24',['ADMINISTRATOR_GUIDE',['../md_Usage_2ADMINISTRATOR__GUIDE.html',1,'']]],
  ['administrator_5fguide_2emd_25',['ADMINISTRATOR_GUIDE.md',['../ADMINISTRATOR__GUIDE_8md.html',1,'']]],
  ['advantages_26',['Advantages',['../md_PROJECT.html#autotoc_md14',1,'']]],
  ['advantages_20of_20the_20doxygen_20site_27',['Advantages of the Doxygen Site',['../md_PROJECT.html#autotoc_md17',1,'']]],
  ['alpha_20version_28',['1.2 Alpha-Version',['../md_Version_2VERSION.html#autotoc_md252',1,'']]],
  ['also_29',['also',['../md_Version_2NAMESPACE.html#autotoc_md229',1,'See Also'],['../md_Version_2FIX.html#autotoc_md217',1,'See Also'],['../md_Version_2FEATURE.html#autotoc_md208',1,'See Also'],['../md_Version_2RELEASE__POLICY.html#autotoc_md239',1,'See Also'],['../md_Version_2CHANGELOG.html#autotoc_md191',1,'See Also'],['../md_Version_2BUG.html#autotoc_md184',1,'See Also'],['../md_Version_2API.html#autotoc_md176',1,'See Also'],['../md_Usage_2USECASES.html#autotoc_md143',1,'See Also'],['../md_PROJECT.html#autotoc_md22',1,'See Also'],['../md_Usage_2ROLES.html#autotoc_md134',1,'See Also'],['../md_README.html#autotoc_md72',1,'See Also'],['../md_Usage_2ACTORS.html#autotoc_md84',1,'See Also'],['../md_Version_2VERSION.html#autotoc_md262',1,'See Also']]],
  ['an_20issue_30',['How to Open an Issue',['../md_README.html#autotoc_md69',1,'']]],
  ['and_20actors_20🎮_31',['Usage and Actors 🎮',['../md_README.html#autotoc_md52',1,'']]],
  ['and_20contribute_20to_20project_32',['Use Case 2 — Fork and Contribute to Project',['../md_Usage_2USECASES.html#autotoc_md140',1,'']]],
  ['and_20dependencies_33',['Prerequisites and Dependencies',['../md_Usage_2ADMINISTRATOR__GUIDE.html#autotoc_md91',1,'']]],
  ['api_34',['API',['../md_Version_2API.html',1,'']]],
  ['api_20development_20🧠_35',['API Development 🧠',['../md_Usage_2DEVELOPMENT__GUIDE.html#autotoc_md118',1,'']]],
  ['api_20reference_36',['API Reference',['../md_Version_2API.html#autotoc_md163',1,'']]],
  ['api_2emd_37',['API.md',['../API_8md.html',1,'']]],
  ['apis_38',['apis',['../md_Version_2API.html#autotoc_md175',1,'How To Develop APIs'],['../namespacemyNamespace.html#autotoc_md124',1,'How to extend APIs'],['../md_Version_2API.html#autotoc_md174',1,'How To Integrate APIs']]],
  ['apis_20through_20namespaces_39',['🧩 How To Address APIs through Namespaces',['../md_Version_2NAMESPACE.html#autotoc_md228',1,'']]],
  ['architecture_40',['🚀 Architecture',['../md_PROJECT.html#autotoc_md10',1,'']]],
  ['as_20administrator_41',['How to access as administrator',['../md_Usage_2ADMINISTRATOR__GUIDE.html#autotoc_md106',1,'']]],
  ['attribution_42',['Attribution',['../md_CODE__OF__CONDUCT.html#autotoc_md6',1,'']]],
  ['authors_20🧑‍💻_43',['Authors 🧑‍💻',['../md_README.html#autotoc_md76',1,'']]]
];
