var searchData=
[
  ['case_201_20—_20generate_20project_20documentation_0',['Use Case 1 — Generate Project Documentation',['../md_Usage_2USECASES.html#autotoc_md139',1,'']]],
  ['case_202_20—_20fork_20and_20contribute_20to_20project_1',['Use Case 2 — Fork and Contribute to Project',['../md_Usage_2USECASES.html#autotoc_md140',1,'']]],
  ['case_203_20—_20report_20a_20bug_2',['Use Case 3 — Report a Bug',['../md_Usage_2USECASES.html#autotoc_md141',1,'']]],
  ['case_204_20—_20update_20project_20version_3',['Use Case 4 — Update Project Version',['../md_Usage_2USECASES.html#autotoc_md142',1,'']]],
  ['cause_4',['cause',['../classexception_1_1ChatbotException.html#acd4758da4b5f425ac89d7354affae522',1,'exception::ChatbotException']]],
  ['cd_20role_20optional_5',['CI/CD Role (Optional)',['../md_Usage_2ROLES.html#autotoc_md132',1,'']]],
  ['cd_20system_20optional_6',['4. CI/CD System (Optional)',['../md_Usage_2ACTORS.html#autotoc_md82',1,'']]],
  ['change_20log_7',['🔄 Change Log',['../md_Version_2CHANGELOG.html#autotoc_md190',1,'']]],
  ['change_20log_20📋_8',['Change Log 📋',['../md_README.html#autotoc_md56',1,'']]],
  ['changelog_9',['CHANGELOG',['../md_Version_2CHANGELOG.html',1,'']]],
  ['changelog_2emd_10',['CHANGELOG.md',['../CHANGELOG_8md.html',1,'']]],
  ['changes_11',['changes',['../md_Version_2API.html#autotoc_md161',1,'↩️ Changes'],['../md_Version_2CHANGELOG.html#autotoc_md189',1,'🔧 Types of Changes']]],
  ['characteristics_12',['Characteristics',['../md_Version_2API.html#autotoc_md156',1,'']]],
  ['chatbotexception_13',['ChatbotException',['../classexception_1_1ChatbotException.html',1,'exception']]],
  ['chatbotexceptioncode_14',['ChatbotExceptionCode',['../classexception_1_1ChatbotException_1_1ChatbotExceptionCode.html',1,'exception::ChatbotException']]],
  ['chatbotexceptionseverity_15',['ChatbotExceptionSeverity',['../classexception_1_1ChatbotException_1_1ChatbotExceptionSeverity.html',1,'exception::ChatbotException']]],
  ['check_5falive_5fbot_16',['check_alive_bot',['../classbot_1_1BotManager.html#a43c1c3b29ca0c3ba28b77fab9933ea86',1,'bot::BotManager']]],
  ['check_5falive_5fbots_17',['check_alive_bots',['../classbot_1_1BotManager.html#a386f86d037e176ba8e7f796af6f5bedb',1,'bot::BotManager']]],
  ['check_5fenv_18',['check_env',['../classenv_1_1Env.html#a257e3cc10abda127dbd9247de41f70b9',1,'env::Env']]],
  ['check_5fngrok_19',['check_ngrok',['../classconfigurator_1_1Configurator.html#aa06514ca8386fc8b9b9a2662d47d8b90',1,'configurator::Configurator']]],
  ['ci_20cd_20role_20optional_20',['CI/CD Role (Optional)',['../md_Usage_2ROLES.html#autotoc_md132',1,'']]],
  ['ci_20cd_20system_20optional_21',['4. CI/CD System (Optional)',['../md_Usage_2ACTORS.html#autotoc_md82',1,'']]],
  ['clone_20repository_22',['Option B — Clone Repository',['../md_Usage_2ADMINISTRATOR__GUIDE.html#autotoc_md95',1,'']]],
  ['code_23',['code',['../namespacecode.html',1,'code'],['../classexception_1_1ChatbotException.html#ac63960d4f08aed90138952b16f1051dc',1,'exception.ChatbotException.code']]],
  ['code_20integration_24',['3️⃣ Source Code Integration',['../md_PROJECT.html#autotoc_md18',1,'']]],
  ['code_20of_20conduct_25',['code of conduct',['../md_README.html#autotoc_md71',1,'4. Code of Conduct'],['../md_CODE__OF__CONDUCT.html',1,'Contributor Covenant Code of Conduct']]],
  ['code_20structure_20🧩_26',['Code Structure 🧩',['../md_Usage_2DEVELOPMENT__GUIDE.html#autotoc_md115',1,'']]],
  ['code_5fof_5fconduct_2emd_27',['CODE_OF_CONDUCT.md',['../CODE__OF__CONDUCT_8md.html',1,'']]],
  ['collection_28',['🧩 Collection',['../md_Version_2API.html#autotoc_md159',1,'']]],
  ['command_29',['command',['../md_Version_2NAMESPACE.html#autotoc_md224',1,'📎 Command'],['../md_Version_2API.html#autotoc_md165',1,'Command']]],
  ['conduct_30',['conduct',['../md_README.html#autotoc_md71',1,'4. Code of Conduct'],['../md_CODE__OF__CONDUCT.html',1,'Contributor Covenant Code of Conduct']]],
  ['conf_5flogger_31',['conf_logger',['../classconfigurator_1_1Configurator.html#a8ea6a72e9b3b395163f0298ac2741306',1,'configurator::Configurator']]],
  ['config_32',['config',['../namespaceconfigurator.html#ac3bde563e1d11281d71d0abcb4bad18f',1,'configurator.config'],['../classlogger_1_1Logger.html#abb337318ffa48ade109a0832fdb7fbf8',1,'logger.Logger.config()']]],
  ['config_5ferror_33',['CONFIG_ERROR',['../classexception_1_1ChatbotException_1_1ChatbotExceptionCode.html#aa835ca6b055bac79c8bd29720780fdfe',1,'exception::ChatbotException::ChatbotExceptionCode']]],
  ['config_5flogger_5ffailed_34',['CONFIG_LOGGER_FAILED',['../classconfigurator_1_1ConfigurationExceptionCode.html#a5fb4d12046d045ebb35767138e378b44',1,'configurator::ConfigurationExceptionCode']]],
  ['config_5funexpected_5ferror_35',['CONFIG_UNEXPECTED_ERROR',['../classconfigurator_1_1ConfigurationExceptionCode.html#af45a0afb41f6cfbb77a9f7ef44210b3e',1,'configurator::ConfigurationExceptionCode']]],
  ['configuration_36',['configuration',['../md_README.html#autotoc_md43',1,'⚙️ Configuration'],['../md_Usage_2ADMINISTRATOR__GUIDE.html#autotoc_md100',1,'Configuration'],['../md_Usage_2ADMINISTRATOR__GUIDE.html#autotoc_md108',1,'How to update configuration']]],
  ['configurationcheckngrokexception_37',['ConfigurationCheckNgrokException',['../classconfigurator_1_1ConfigurationCheckNgrokException.html',1,'configurator']]],
  ['configurationexception_38',['ConfigurationException',['../classconfigurator_1_1ConfigurationException.html',1,'configurator']]],
  ['configurationexceptioncode_39',['ConfigurationExceptionCode',['../classconfigurator_1_1ConfigurationExceptionCode.html',1,'configurator']]],
  ['configurationhttprequestexcpetion_40',['ConfigurationHTTPRequestExcpetion',['../classconfigurator_1_1ConfigurationHTTPRequestExcpetion.html',1,'configurator']]],
  ['configurationhttprequestmethodexcpetion_41',['ConfigurationHTTPRequestMethodExcpetion',['../classconfigurator_1_1ConfigurationHTTPRequestMethodExcpetion.html',1,'configurator']]],
  ['configurationhttprequestretryexcpetion_42',['ConfigurationHTTPRequestRetryExcpetion',['../classconfigurator_1_1ConfigurationHTTPRequestRetryExcpetion.html',1,'configurator']]],
  ['configurationhttprequesttimeoutexcpetion_43',['ConfigurationHTTPRequestTimeoutExcpetion',['../classconfigurator_1_1ConfigurationHTTPRequestTimeoutExcpetion.html',1,'configurator']]],
  ['configurationsettelegramwebhookexception_44',['ConfigurationSetTelegramWebhookException',['../classconfigurator_1_1ConfigurationSetTelegramWebhookException.html',1,'configurator']]],
  ['configurationstartngrokexception_45',['ConfigurationStartNgrokException',['../classconfigurator_1_1ConfigurationStartNgrokException.html',1,'configurator']]],
  ['configurationstopngrokexception_46',['ConfigurationStopNgrokException',['../classconfigurator_1_1ConfigurationStopNgrokException.html',1,'configurator']]],
  ['configurationverifyngrokexception_47',['ConfigurationVerifyNgrokException',['../classconfigurator_1_1ConfigurationVerifyNgrokException.html',1,'configurator']]],
  ['configurator_48',['configurator',['../namespaceconfigurator.html',1,'configurator'],['../classconfigurator_1_1Configurator.html',1,'configurator.Configurator']]],
  ['configurator_2epy_49',['configurator.py',['../configurator_8py.html',1,'']]],
  ['configure_50',['configure',['../classconfigurator_1_1Configurator.html#aea5dbc28f772e392d8a96958ca403cfd',1,'configurator.Configurator.configure()'],['../classweb__server_1_1WebApp.html#a857b65105ee8b50f7e981cbde3e96c8f',1,'web_server.WebApp.configure()']]],
  ['consume_5fincoming_5fqueue_51',['consume_incoming_queue',['../classbot_1_1Bot.html#afa36ac420df45dec04821ad7839ef433',1,'bot::Bot']]],
  ['consume_5foutgoing_5fqueue_52',['consume_outgoing_queue',['../classbot_1_1Bot.html#abc2caaa21ed664e53259802db8bbf058',1,'bot::Bot']]],
  ['consumer_5fin_5fthread_53',['consumer_in_thread',['../classbot_1_1Bot.html#a87e70e3fb06627351b11db45260eb012',1,'bot::Bot']]],
  ['consumer_5fout_5fthread_54',['consumer_out_thread',['../classbot_1_1Bot.html#a840f4ce430e2db8135638d5604988685',1,'bot::Bot']]],
  ['contact_20us_20☎️_55',['contact us ☎️',['../md_Version_2VERSION.html#autotoc_md264',1,'Contact us ☎️'],['../md_Version_2API.html#autotoc_md178',1,'Contact us ☎️'],['../md_Usage_2ROLES.html#autotoc_md136',1,'Contact us ☎️'],['../md_Version_2RELEASE__POLICY.html#autotoc_md241',1,'Contact us ☎️'],['../md_Version_2NAMESPACE.html#autotoc_md231',1,'Contact us ☎️'],['../md_Version_2FIX.html#autotoc_md219',1,'Contact us ☎️'],['../md_Version_2FEATURE.html#autotoc_md210',1,'Contact us ☎️'],['../md_Usage_2USECASES.html#autotoc_md145',1,'Contact us ☎️'],['../md_Usage_2USER__GUIDE.html#autotoc_md154',1,'Contact Us ☎️'],['../md_Version_2CHANGELOG.html#autotoc_md193',1,'Contact us ☎️'],['../md_Version_2BUG.html#autotoc_md186',1,'Contact us ☎️'],['../namespacemyNamespace.html#autotoc_md127',1,'Contact Us ☎️'],['../md_Usage_2ADMINISTRATOR__GUIDE.html#autotoc_md111',1,'Contact us ☎️'],['../md_Usage_2ACTORS.html#autotoc_md86',1,'Contact us ☎️'],['../md_README.html#autotoc_md74',1,'Contact us ☎️'],['../md_PROJECT.html#autotoc_md24',1,'Contact us ☎️']]],
  ['contact_5fus_56',['CONTACT_US',['../md_CONTACT__US.html',1,'']]],
  ['contact_5fus_2emd_57',['CONTACT_US.md',['../CONTACT__US_8md.html',1,'']]],
  ['contents_58',['contents',['../md_Version_2BUG.html#autotoc_md180',1,'📓 Table of Contents'],['../md_Version_2RELEASE__POLICY.html#autotoc_md233',1,'📓 Table of Contents'],['../md_Version_2NAMESPACE.html#autotoc_md221',1,'📓 Table of Contents'],['../md_PROJECT.html#autotoc_md7',1,'📓 Table of Contents'],['../md_Version_2FIX.html#autotoc_md212',1,'📓 Table of Contents'],['../md_Version_2FEATURE.html#autotoc_md195',1,'📓 Table of Contents'],['../md_README.html#autotoc_md26',1,'📓 Table of Contents'],['../md_Version_2CHANGELOG.html#autotoc_md188',1,'📓 Table of Contents'],['../md_Usage_2DEVELOPMENT__GUIDE.html#autotoc_md112',1,'📓 Table of Contents'],['../md_Usage_2ADMINISTRATOR__GUIDE.html#autotoc_md87',1,'📓 Table of Contents'],['../md_Usage_2USER__GUIDE.html#autotoc_md146',1,'📓 Table of Contents'],['../md_Version_2API.html#autotoc_md155',1,'📓 Table of Contents'],['../md_README.html#autotoc_md61',1,'Table of Contents'],['../md_Version_2VERSION.html#autotoc_md243',1,'Table of Contents']]],
  ['contribute_20to_20project_59',['Use Case 2 — Fork and Contribute to Project',['../md_Usage_2USECASES.html#autotoc_md140',1,'']]],
  ['contributing_20👋_60',['Contributing 👋',['../md_README.html#autotoc_md60',1,'']]],
  ['contribution_20rules_61',['General Contribution Rules',['../md_README.html#autotoc_md62',1,'']]],
  ['contributor_20covenant_20code_20of_20conduct_62',['Contributor Covenant Code of Conduct',['../md_CODE__OF__CONDUCT.html',1,'']]],
  ['control_63',['control',['../md_Version_2NAMESPACE.html#autotoc_md223',1,'📎 Control'],['../md_Version_2API.html#autotoc_md164',1,'Control']]],
  ['conventions_64',['Naming conventions',['../md_Usage_2DEVELOPMENT__GUIDE.html#autotoc_md116',1,'']]],
  ['conversation_5fhistory_65',['conversation_history',['../namespacellm.html#aed0aaeb40c1c1b4d35a9502e8c6de35a',1,'llm']]],
  ['covenant_20code_20of_20conduct_66',['Contributor Covenant Code of Conduct',['../md_CODE__OF__CONDUCT.html',1,'']]],
  ['create_5fbot_67',['create_bot',['../classbot_1_1BotManager.html#a2e8fcc3964b3cbe2c48869dc86bfa960',1,'bot::BotManager']]],
  ['create_5fif_5fnot_5fexist_5fand_5fstart_5fbot_68',['create_if_not_exist_and_start_bot',['../classbot_1_1BotManager.html#a476223236141f8727739094c156b8790',1,'bot::BotManager']]],
  ['create_5fif_5fnot_5fexist_5fbot_69',['create_if_not_exist_bot',['../classbot_1_1BotManager.html#add838a9111964ac3ef46d63d6dd640d5',1,'bot::BotManager']]],
  ['critical_70',['critical',['../classlogger_1_1Logger.html#af7cf7a2c19b61d6b659c840eee66caac',1,'logger.Logger.critical()'],['../classexception_1_1ChatbotException_1_1ChatbotExceptionSeverity.html#ae83bf946563be705cf17bf3d571248dc',1,'exception.ChatbotException.ChatbotExceptionSeverity.CRITICAL']]]
];
