READMETemplate: configurator.Configurator Class Reference
configurator.Configurator Class Reference
Public Member Functions
def __init__ (self, str ngrok_path, int ngrok_port, str ngrok_host, str ngrok_proto, str ngrok_tunnels_api, str ngrok_endpoint_visibility, str tg_bot_webhook_method, str tg_bot_set_webhook_api)
tuple[bool, str|None] check_ngrok (self)
def configure (self)
def http_request_with_retry (self, str method, str url, int max_retries=5, float delay=1.0, **kwargs)
def set_telegram_webhook (self, str ngrok_endpoint)
str start_ngrok (self, int max_retries=5, float delay=1.0)
def stop_ngrok (self)
bool verify_ngrok (self)
Public Attributes
conf_logger
ngrok_endpoint
ngrok_endpoint_visibility
ngrok_host
ngrok_path
ngrok_port
ngrok_process
ngrok_proto
ngrok_tunnels_api
tg_bot_set_webhook_api
tg_bot_webhook_method
Detailed Description
Definition at line 46 of file configurator.py.
Constructor & Destructor Documentation
__init__()
def configurator.Configurator.__init__ (self, str ngrok_path, int ngrok_port, str ngrok_host, str ngrok_proto, str ngrok_tunnels_api, str ngrok_endpoint_visibility, str tg_bot_webhook_method, str tg_bot_set_webhook_api)
Definition at line 47 of file configurator.py.
     def __init__(self, ngrok_path: str, ngrok_port: int, ngrok_host: str, ngrok_proto: str,
                  ngrok_tunnels_api: str, ngrok_endpoint_visibility: str,
                  tg_bot_webhook_method: str, tg_bot_set_webhook_api: str):
         self.ngrok_path = environ.NGROK_PATH
         self.ngrok_port = environ.NGROK_PORT
         self.ngrok_host = environ.NGROK_HOST
         self.ngrok_proto = environ.NGROK_PROTO
         self.ngrok_tunnels_api = environ.NGROK_TUNNELS_API
         self.ngrok_endpoint_visibility = environ.NGROK_URL_VISIBILITY
         self.ngrok_endpoint = None
         self.ngrok_process = None
         self.tg_bot_set_webhook_api = environ.TELEGRAM_BOT_SET_WEBHOOK_API
         self.tg_bot_webhook_method = environ.TELEGRAM_BOT_WEBHOOK_METHOD
         self.conf_logger = Logger("configurator", enable_file_handler=True,
                                   enable_stream_handler=False, enable_syslog_handler=False)
Member Function Documentation
check_ngrok()
tuple[bool, str | None] configurator.Configurator.check_ngrok (self)
Definition at line 177 of file configurator.py.
     def check_ngrok(self) -> tuple[bool, str | None]:
         try:
             response = self.http_request_with_retry("get", self.ngrok_tunnels_api)
             tunnels = response.json().get("tunnels", [])
             for tunnel in tunnels:
                 if tunnel.get("proto") == self.ngrok_proto:
                     self.ngrok_endpoint = tunnel["public_url"]
                     return True, self.ngrok_endpoint
             return False, None
         except ConfigurationHTTPRequestMethodExcpetion as me:
             raise ConfigurationCheckNgrokException(
                 f"Ngrok check failed: invalid HTTP method ({me})",
                 code=ConfigurationExceptionCode.HTTP_METHOD_ERROR,
                 cause=me
             )
         except ConfigurationHTTPRequestTimeoutExcpetion as te:
             raise ConfigurationCheckNgrokException(
                 f"Ngrok check failed: timeout ({te})",
                 code=ConfigurationExceptionCode.HTTP_TIMEOUT,
                 cause=te
             )
         except ConfigurationHTTPRequestRetryExcpetion as re:
             raise ConfigurationCheckNgrokException(
                 f"Ngrok check failed after retries: {re}",
                 code=ConfigurationExceptionCode.NGROK_CHECK_FAILED,
                 cause=re
             )
         except requests.RequestException as re:
             self.conf_logger.warning(f"Ngrok connection failed: {re}")
             return False, None
         except Exception as e:
             self.conf_logger.critical("Unexpected error during ngrok check")
             raise ConfigurationCheckNgrokException(
                 "Unexpected error during ngrok check",
                 code=ConfigurationExceptionCode.NGROK_CHECK_FAILED,
                 cause=e
             )
References configurator.Configurator.conf_logger, configurator.Configurator.http_request_with_retry(), configurator.Configurator.ngrok_endpoint, configurator.Configurator.ngrok_proto, and configurator.Configurator.ngrok_tunnels_api.
Referenced by configurator.Configurator.verify_ngrok().
configure()
def configurator.Configurator.configure (self)
Definition at line 291 of file configurator.py.
     def configure(self):
         try:
             self.conf_logger.config()
             endpoint = self.start_ngrok()
             self.set_telegram_webhook(endpoint)
             self.verify_ngrok()
         except LogConfigurationException as lce:
             self.conf_logger.critical(f"Logger configuration failed: {lce}")
             raise ConfigurationException(
                 "Logger configuration failed",
                 code=ConfigurationExceptionCode.CONFIG_LOGGER_FAILED,
                 cause=lce
             )
         except ConfigurationStartNgrokException as sne:
             self.conf_logger.critical(f"Ngrok start failed: {sne}")
             raise ConfigurationException(
                 "Configuration failed during Ngrok start",
                 code=ConfigurationExceptionCode.NGROK_START_FAILED,
                 cause=sne
             )
         except ConfigurationVerifyNgrokException as vne:
             self.conf_logger.critical(f"Ngrok verification failed: {vne}")
             raise ConfigurationException(
                 "Configuration failed during Ngrok verification",
                 code=ConfigurationExceptionCode.NGROK_VERIFY_FAILED,
                 cause=vne
             )
         except ConfigurationSetTelegramWebhookException as twe:
             self.conf_logger.critical(f"Telegram webhook setup failed: {twe}")
             raise ConfigurationException(
                 "Configuration failed during Telegram webhook setup",
                 code=ConfigurationExceptionCode.TELEGRAM_WEBHOOK_UNEXPECTED_ERROR,
                 cause=twe
             )
         except ConfigurationException as ce:
             self.conf_logger.critical(f"Generic configuration failure: {ce}")
             raise ConfigurationException(
                 "Generic configuration failure",
                 code=ConfigurationExceptionCode.CONFIG_UNEXPECTED_ERROR,
                 cause=ce
             )
         except Exception as e:
             self.conf_logger.critical("Unexpected error during configuration")
             raise ConfigurationException(
                 "Unexpected configuration failure",
                 code=ConfigurationExceptionCode.CONFIG_UNEXPECTED_ERROR,
                 cause=e
             )
References configurator.Configurator.conf_logger, configurator.Configurator.set_telegram_webhook(), configurator.Configurator.start_ngrok(), and configurator.Configurator.verify_ngrok().
http_request_with_retry()
def configurator.Configurator.http_request_with_retry (self, str method, str url, int max_retries = 5, float delay = 1.0, ** kwargs)
Definition at line 66 of file configurator.py.
     def http_request_with_retry(self, method: str, url: str, max_retries: int = 5, delay: float = 1.0, **kwargs):
         for attempt in range(1, max_retries + 1):
             try:
                 if method.lower() == "get":
                     response = requests.get(url, timeout=5, **kwargs)
                 elif method.lower() == "post":
                     response = requests.post(url, timeout=5, **kwargs)
                 else:
                     raise ConfigurationHTTPRequestMethodExcpetion(
                         f"Unsupported HTTP method: {method}",
                         code=ConfigurationExceptionCode.HTTP_METHOD_ERROR
                     )
                 response.raise_for_status()
                 return response
             except requests.Timeout as e:
                 if attempt == max_retries:
                     raise ConfigurationHTTPRequestTimeoutExcpetion(
                         f"HTTP {method.upper()} timeout after {max_retries} attempts",
                         code=ConfigurationExceptionCode.HTTP_TIMEOUT,
                         cause=e
                     )
             except requests.RequestException as e:
                 self.conf_logger.warning(f"HTTP {method.upper()} failed (attempt {attempt}/{max_retries}): {e}")
                 if attempt == max_retries:
                     raise ConfigurationHTTPRequestRetryExcpetion(f"HTTP {method.upper()} failed after {max_retries} attempts", code=ConfigurationExceptionCode.HTTP_REQUEST_TIMEOUT, cause=e)
             time.sleep(delay)
References configurator.Configurator.conf_logger.
Referenced by configurator.Configurator.check_ngrok(), configurator.Configurator.set_telegram_webhook(), and configurator.Configurator.start_ngrok().
set_telegram_webhook()
def configurator.Configurator.set_telegram_webhook (self, str ngrok_endpoint)
Definition at line 247 of file configurator.py.
     def set_telegram_webhook(self, ngrok_endpoint: str):
         try:
             self.conf_logger.info("Set telegram webhook")
             webhook_api = f"{ngrok_endpoint}{self.tg_bot_webhook_method}"
             self.conf_logger.info(f"Set telegram webhook api {webhook_api} by using api {self.tg_bot_set_webhook_api}")
             response = self.http_request_with_retry("post", self.tg_bot_set_webhook_api, data={"url": webhook_api})
             self.conf_logger.info("Telegram response: " + str(response.json()))
         except ConfigurationHTTPRequestMethodExcpetion as me:
             raise ConfigurationSetTelegramWebhookException(
                 f"Invalid HTTP method used for webhook: {me}",
                 code=ConfigurationExceptionCode.TELEGRAM_WEBHOOK_METHOD_ERROR,
                 cause=me
             )
         except ConfigurationHTTPRequestTimeoutExcpetion as te:
             raise ConfigurationSetTelegramWebhookException(
                 f"Webhook setup failed due to timeout: {te}",
                 code=ConfigurationExceptionCode.HTTP_TIMEOUT,
                 cause=te
             )
         except ConfigurationHTTPRequestRetryExcpetion as re:
             raise ConfigurationSetTelegramWebhookException(
                 f"Webhook setup failed after retries: {re}",
                 code=ConfigurationExceptionCode.TELEGRAM_WEBHOOK_HTTP_ERROR,
                 cause=re
             )
         except requests.RequestException as re:
             raise ConfigurationSetTelegramWebhookException(
                 f"Webhook setup failed due to HTTP/network error: {re}",
                 code=ConfigurationExceptionCode.TELEGRAM_WEBHOOK_HTTP_ERROR,
                 cause=re
             )
         except Exception as e:
             raise ConfigurationSetTelegramWebhookException(
                 "Unexpected error while setting Telegram webhook",
                 code=ConfigurationExceptionCode.TELEGRAM_WEBHOOK_UNEXPECTED_ERROR,
                 cause=e
             )
References configurator.Configurator.conf_logger, configurator.Configurator.http_request_with_retry(), and configurator.Configurator.tg_bot_set_webhook_api.
Referenced by configurator.Configurator.configure().
start_ngrok()
str configurator.Configurator.start_ngrok (self, int max_retries = 5, float delay = 1.0)
Definition at line 95 of file configurator.py.
     def start_ngrok(self, max_retries: int = 5, delay: float = 1.0) -> str:
         try:
             self.ngrok_process = subprocess.Popen(
                 [self.ngrok_path, self.ngrok_proto, f"{self.ngrok_host}:{self.ngrok_port}"],
                 stdout=subprocess.DEVNULL,
                 stderr=subprocess.STDOUT
             )
             for attempt in range(max_retries):
                 try:
                     response = self.http_request_with_retry("get", self.ngrok_tunnels_api, max_retries=3, delay=delay)
                     tunnels = response.json().get("tunnels", [])
                     for tunnel in tunnels:
                         if tunnel.get("proto") == self.ngrok_proto:
                             self.ngrok_endpoint = tunnel[self.ngrok_endpoint_visibility]
                             atexit.register(self.stop_ngrok)
                             return self.ngrok_endpoint
                 except ConfigurationHTTPRequestMethodExcpetion as me:
                     raise ConfigurationStartNgrokException(
                         f"Ngrok tunnel check failed: invalid HTTP method ({me})",
                         code=ConfigurationExceptionCode.HTTP_METHOD_ERROR,
                         cause=me
                     )
                 except ConfigurationHTTPRequestTimeoutExcpetion as te:
                     raise ConfigurationStartNgrokException(
                         f"Ngrok tunnel check failed: timeout ({te})",
                         code=ConfigurationExceptionCode.HTTP_TIMEOUT,
                         cause=te
                     )
                 except ConfigurationHTTPRequestRetryExcpetion as re:
                     self.conf_logger.warning(f"Ngrok tunnel API not reachable (attempt {attempt+1}/{max_retries}): {re}")
                     if attempt == max_retries - 1:
                         raise ConfigurationStartNgrokException(
                             "Ngrok tunnel API unreachable after retries",
                             code=ConfigurationExceptionCode.NGROK_NOT_READY,
                             cause=re
                         )
                     time.sleep(delay)
                 except requests.RequestException as re:
                     self.conf_logger.warning(f"Ngrok not ready, retrying... ({attempt+1}/{max_retries})")
                     if attempt == max_retries - 1:
                         raise ConfigurationStartNgrokException(
                             "Ngrok did not respond within retries",
                             code=ConfigurationExceptionCode.NGROK_NOT_READY,
                             cause=re
                         )
                     time.sleep(delay)
             raise ConfigurationStartNgrokException(
                 "Unable to start ngrok service after retries",
                 code=ConfigurationExceptionCode.NGROK_NOT_READY
             )
         except ConfigurationStartNgrokException:
             raise
         except Exception as e:
             self.conf_logger.critical("Failed to start ngrok")
             raise ConfigurationStartNgrokException(
                 "Ngrok start failure",
                 code=ConfigurationExceptionCode.NGROK_START_FAILED,
                 cause=e
             )
References configurator.Configurator.conf_logger, configurator.Configurator.http_request_with_retry(), configurator.Configurator.ngrok_endpoint, configurator.Configurator.ngrok_endpoint_visibility, configurator.Configurator.ngrok_path, configurator.Configurator.ngrok_process, configurator.Configurator.ngrok_proto, configurator.Configurator.ngrok_tunnels_api, and configurator.Configurator.stop_ngrok().
Referenced by configurator.Configurator.configure().
stop_ngrok()
def configurator.Configurator.stop_ngrok (self)
Definition at line 162 of file configurator.py.
     def stop_ngrok(self):
         try:
             if self.ngrok_process:
                 self.conf_logger.info("Stopping ngrok service")
                 self.ngrok_process.terminate()
                 self.ngrok_process = None
                 self.conf_logger.info("Ngrok process terminated")
         except Exception as e:
             self.conf_logger.critical("Failed to stop ngrok")
             raise ConfigurationStopNgrokException(
                 "Ngrok stop failure",
                 code=ConfigurationExceptionCode.NGROK_STOP_FAILED,
                 cause=e
             )
References configurator.Configurator.conf_logger, and configurator.Configurator.ngrok_process.
Referenced by configurator.Configurator.start_ngrok().
verify_ngrok()
bool configurator.Configurator.verify_ngrok (self)
Definition at line 220 of file configurator.py.
     def verify_ngrok(self) -> bool:
         try:
             self.conf_logger.info("Verify ngrok connection")
             alive, endpoint = self.check_ngrok()
             if alive:
                 self.conf_logger.info(f"Ngrok is alive: {endpoint}")
                 return True
             else:
                 raise ConfigurationVerifyNgrokException(
                     "Ngrok is NOT alive",
                     code=ConfigurationExceptionCode.NGROK_VERIFY_FAILED
                 )
         except ConfigurationCheckNgrokException as ccne:
             raise ConfigurationVerifyNgrokException(
                 f"Verification failed due to check error: {ccne}",
                 code=ConfigurationExceptionCode.NGROK_VERIFY_FAILED,
                 cause=ccne
             )
         except Exception as e:
             raise ConfigurationVerifyNgrokException(
                 "Unexpected error during ngrok verification",
                 code=ConfigurationExceptionCode.NGROK_VERIFY_FAILED,
                 cause=e
             )
References configurator.Configurator.check_ngrok(), and configurator.Configurator.conf_logger.
Referenced by configurator.Configurator.configure().
Member Data Documentation
conf_logger
configurator.Configurator.conf_logger
Definition at line 60 of file configurator.py.
Referenced by configurator.Configurator.check_ngrok(), configurator.Configurator.configure(), configurator.Configurator.http_request_with_retry(), configurator.Configurator.set_telegram_webhook(), configurator.Configurator.start_ngrok(), configurator.Configurator.stop_ngrok(), and configurator.Configurator.verify_ngrok().
ngrok_endpoint
configurator.Configurator.ngrok_endpoint
Definition at line 55 of file configurator.py.
Referenced by configurator.Configurator.check_ngrok(), and configurator.Configurator.start_ngrok().
ngrok_endpoint_visibility
configurator.Configurator.ngrok_endpoint_visibility
Definition at line 54 of file configurator.py.
Referenced by configurator.Configurator.start_ngrok().
ngrok_host
configurator.Configurator.ngrok_host
Definition at line 51 of file configurator.py.
ngrok_path
configurator.Configurator.ngrok_path
Definition at line 49 of file configurator.py.
Referenced by configurator.Configurator.start_ngrok().
ngrok_port
configurator.Configurator.ngrok_port
Definition at line 50 of file configurator.py.
ngrok_process
configurator.Configurator.ngrok_process
Definition at line 56 of file configurator.py.
Referenced by configurator.Configurator.start_ngrok(), and configurator.Configurator.stop_ngrok().
ngrok_proto
configurator.Configurator.ngrok_proto
Definition at line 52 of file configurator.py.
Referenced by configurator.Configurator.check_ngrok(), and configurator.Configurator.start_ngrok().
ngrok_tunnels_api
configurator.Configurator.ngrok_tunnels_api
Definition at line 53 of file configurator.py.
Referenced by configurator.Configurator.check_ngrok(), and configurator.Configurator.start_ngrok().
tg_bot_set_webhook_api
configurator.Configurator.tg_bot_set_webhook_api
Definition at line 57 of file configurator.py.
Referenced by configurator.Configurator.set_telegram_webhook().
tg_bot_webhook_method
configurator.Configurator.tg_bot_webhook_method
Definition at line 58 of file configurator.py.
Referenced by web_server.WebApp._register_routes().
The documentation for this class was generated from the following file:
src/configurator.py
⬇️ Download 🐙 View on GitHub
© 2025 Giuseppe Pedone — GitHub