READMETemplate: bot.BotManager Class Reference
bot.BotManager Class Reference
Public Member Functions
def __del__ (self)
def __init__ (self, float run_cycle_time=1.0)
def bots_info_json (self, max_queue_items=None)
str bots_info_str (self, max_queue_items=5)
bool check_alive_bot (self, str bot_type, str id)
bool check_alive_bots (self)
Bot create_bot (self, str bot_type, str id, Optional[Callable[[Message], bool]] on_incoming_message=None, Optional[Callable[[Message], bool]] on_outgoing_message=None)
Bot create_if_not_exist_and_start_bot (self, str bot_type, str id)
Bot create_if_not_exist_bot (self, str bot_type, str id)
Union[Bot, None] get_bot (self, str bot_type, str id)
Dict[str, Dict[str, str]] list_bots (self)
bool maintain_alive_bots (self)
int receive_message_from_bot (self, str bot_type, str id, str payload)
def run (self)
int send_message_on_bot (self, str bot_type, str id, str payload, str params=None, str headers=None)
def start (self, str thread_name="BotManagerThread", bool daemon=True, **thread_kwargs)
Bot start_bot (self, str bot_type, str id, Optional[Callable[[Message], bool]] on_incoming_message=None, Optional[Callable[[Message], bool]] on_outgoing_message=None)
def stop (self)
def stop_bots (self)
Bot terminate_and_restart_bot (self, str bot_type, str id)
def terminate_bot (self, str bot_type, str id)
def terminate_bot_by_instance (self, Bot bot)
Public Attributes
bot_manager_logger
bot_manager_stop_event
run_cycle_time
run_thread
Detailed Description
Definition at line 525 of file bot.py.
Constructor & Destructor Documentation
__init__()
def bot.BotManager.__init__ (self, float run_cycle_time = 1.0)
Definition at line 527 of file bot.py.
     def __init__(self, run_cycle_time: float = 1.0):
         self.bots: Dict[str, Dict[str, Bot]] = {
             "telegram": {},
             "facebook": {},
             "whatsapp": {}
         }
         self.run_cycle_time = run_cycle_time
         self.run_thread: Optional[threading.Thread] = None
         self.bot_manager_stop_event = threading.Event()
         self.bot_manager_logger = Logger(
             name=f"bot-manager", enable_file_handler=True, enable_syslog_handler=True
         )
         self.bot_manager_logger.config(min_level="DEBUG")
         self.bot_manager_logger.info("Bot Manager created")
         atexit.register(self.stop)
__del__()
def bot.BotManager.__del__ (self)
Definition at line 751 of file bot.py.
     def __del__(self):
         self.stop()
 TelegramBot.send_message_api = environ.TELEGRAM_BOT_SEND_MESSAGE_API
 WhatsappBot.send_message_api = environ.WHATSAPP_BOT_SEND_MESSAGE_API
 FacebookBot.send_message_api = environ.FACEBOOK_BOT_SEND_MESSAGE_API
 TelegramBot.token = environ.TELEGRAM_TOKEN
 WhatsappBot.token = environ.WHATSAPP_TOKEN
 FacebookBot.token = environ.FACEBOOK_TOKEN
References bot.Bot.stop(), and bot.BotManager.stop().
Member Function Documentation
bots_info_json()
def bot.BotManager.bots_info_json (self, max_queue_items = None)
Definition at line 591 of file bot.py.
     def bots_info_json(self, max_queue_items=None):
         data = {}
         for bot_type, bots in self.bots.items():
             data[bot_type] = {}
             for bot_id, bot in bots.items():
                 data[bot_type][bot_id] = bot.serialize(max_queue_items)
         return json.dumps(data, indent=2)
bots_info_str()
str bot.BotManager.bots_info_str (self, max_queue_items = 5)
Definition at line 599 of file bot.py.
     def bots_info_str(self, max_queue_items=5) -> str:
         parts = []
         for bot_type, bots in self.bots.items():
             for bot_id, bot in bots.items():
                 ser = bot.serialize(max_queue_items)
                 attrs = ", ".join(f"{k}={v}" for k, v in ser["attributes"].items())
                 parts.append(f"[BotType={bot_type}, BotId={bot_id}, Class={ser['class']}, {attrs}]")
         return " | ".join(parts)
check_alive_bot()
bool bot.BotManager.check_alive_bot (self, str bot_type, str id)
Definition at line 696 of file bot.py.
     def check_alive_bot(self, bot_type: str, id: str) -> bool:
         bot = self.bots.get(bot_type, {}).get(id)
         if not bot:
             self.bot_manager_logger.warning(f"Bot {id} of type {bot_type} not found")
             return False
         try:
             if not bot.alive():
                 self.bot_manager_logger.warning(f"Bot {id} of type {bot_type} not alive")
                 return False
             return True
         except Exception as e:
             self.bot_manager_logger.warning(
                 f"Unable to check bot {id} of type {bot_type} aliveness: {e}"
             )
             return False
References bot.BotManager.bot_manager_logger.
check_alive_bots()
bool bot.BotManager.check_alive_bots (self)
Definition at line 620 of file bot.py.
     def check_alive_bots(self) -> bool:
         for bot_type, bots in list(self.bots.items()):
             for id, bot in list(bots.items()):
                 try:
                     if not bot.alive():
                         self.bot_manager_logger.warning(
                             f"Bot {id} of type {bot_type} is not alive"
                         )
                         return False
                 except Exception as e:
                     self.bot_manager_logger.warning(
                         f"Unable to check bot {id} of type {bot_type} aliveness: {e}"
                     )
         return True
References bot.BotManager.bot_manager_logger.
create_bot()
Bot bot.BotManager.create_bot (self, str bot_type, str id, Optional[Callable[[Message], bool]] on_incoming_message = None, Optional[Callable[[Message], bool]] on_outgoing_message = None)
Definition at line 646 of file bot.py.
     def create_bot(self, bot_type: str, id: str,
                    on_incoming_message: Optional[Callable[[Message], bool]] = None,
                    on_outgoing_message: Optional[Callable[[Message], bool]] = None) -> Bot:
         bot_type = bot_type.lower()
         try:
             if bot_type == "telegram":
                 bot = TelegramBot(id, on_incoming_message, on_outgoing_message)
             elif bot_type == "facebook":
                 bot = FacebookBot(id, on_incoming_message, on_outgoing_message)
             elif bot_type == "whatsapp":
                 bot = WhatsappBot(id, on_incoming_message, on_outgoing_message)
             else:
                 raise BotManagerException(f"Unsupported bot type: {bot_type}")
             self.bots[bot_type][id] = bot
             return bot
         except Exception as e:
             self.bot_manager_logger.error(f"Failed to create bot {id} of type {bot_type}: {e}")
             raise BotManagerBotException(f"Bot creation failed: {e}") from e
References bot.BotManager.bot_manager_logger.
Referenced by bot.BotManager.create_if_not_exist_bot(), and bot.BotManager.terminate_and_restart_bot().
create_if_not_exist_and_start_bot()
Bot bot.BotManager.create_if_not_exist_and_start_bot (self, str bot_type, str id)
Definition at line 665 of file bot.py.
     def create_if_not_exist_and_start_bot(self, bot_type: str, id: str) -> Bot:
         bot = self.create_if_not_exist_bot(bot_type=bot_type, id=id)
         bot.start(consumer_out_thread_name=f"BotConsumerOutgoingThread-{id}", consumer_in_thread_name=f"BotConsumerIncomingThread-{id}", daemon=False)
         return bot
References bot.BotManager.create_if_not_exist_bot().
create_if_not_exist_bot()
Bot bot.BotManager.create_if_not_exist_bot (self, str bot_type, str id)
Definition at line 670 of file bot.py.
     def create_if_not_exist_bot(self, bot_type: str, id: str) -> Bot:
         bot = self.bots.get(bot_type, {}).get(id)
         if not bot:
             bot = self.create_bot(bot_type=bot_type, id=id)
             return bot
         else:
             return bot
References bot.BotManager.create_bot().
Referenced by bot.BotManager.create_if_not_exist_and_start_bot(), bot.BotManager.receive_message_from_bot(), bot.BotManager.send_message_on_bot(), and bot.BotManager.start_bot().
get_bot()
Union[Bot, None] bot.BotManager.get_bot (self, str bot_type, str id)
Definition at line 693 of file bot.py.
     def get_bot(self, bot_type: str, id: str) -> Union[Bot, None]:
         return self.bots.get(bot_type, {}).get(id)
Referenced by bot.BotManager.terminate_bot().
list_bots()
Dict[str, Dict[str, str]] bot.BotManager.list_bots (self)
Definition at line 585 of file bot.py.
     def list_bots(self) -> Dict[str, Dict[str, str]]:
         return {
             bot_type: {id: bot.__class__.__name__ for id, bot in bots.items()}
             for bot_type, bots in self.bots.items()
         }
maintain_alive_bots()
bool bot.BotManager.maintain_alive_bots (self)
Definition at line 608 of file bot.py.
     def maintain_alive_bots(self) -> bool:
         for bot_type, bots in list(self.bots.items()):
             for bot_id, bot in list(bots.items()):
                 try:
                     if not bot.alive():
                         self.bot_manager_logger.warning(f"Bot {bot_id} of type {bot_type} not alive, restarting...")
                         self.terminate_and_restart_bot(bot_type, bot_id)
                 except Exception as e:
                     self.bot_manager_logger.critical(f"Unable to maintain bot {bot_id} alive: {e}")
                     raise BotManagerAliveCheckException(f"Failed to maintain bot {bot_id}: {e}") from e
         return True
References bot.BotManager.bot_manager_logger, and bot.BotManager.terminate_and_restart_bot().
Referenced by bot.BotManager.run().
receive_message_from_bot()
int bot.BotManager.receive_message_from_bot (self, str bot_type, str id, str payload)
Definition at line 743 of file bot.py.
     def receive_message_from_bot(self, bot_type: str, id: str, payload: str) -> int:
         bot = self.create_if_not_exist_bot(bot_type, id)
         try:
             return bot.receive_message(payload=payload)
         except Exception as e:
             self.bot_manager_logger.error(f"Receive message failed on bot {id}: {e}")
             raise BotManagerBotException(f"Receive message failed: {e}") from e
References bot.BotManager.bot_manager_logger, and bot.BotManager.create_if_not_exist_bot().
run()
def bot.BotManager.run (self)
Definition at line 559 of file bot.py.
     def run(self):
         while not self.bot_manager_stop_event.is_set():
             try:
                 sleep(self.run_cycle_time)
                 self.bot_manager_logger.debug(f"Current Bots - {self.bots_info_str()}")
                 self.maintain_alive_bots()
             except Exception as e:
                 self.bot_manager_logger.warning(f"Exception in Bot Manager run loop: {e}")
                 raise BotManagerThreadException(f"Run loop error: {e}") from e
References bot.BotManager.bot_manager_logger, bot.BotManager.bot_manager_stop_event, bot.BotManager.maintain_alive_bots(), and bot.BotManager.run_cycle_time.
send_message_on_bot()
int bot.BotManager.send_message_on_bot (self, str bot_type, str id, str payload, str params = None, str headers = None)
Definition at line 735 of file bot.py.
     def send_message_on_bot(self, bot_type: str, id: str, payload: str, params: str = None, headers: str = None) -> int:
         bot = self.create_if_not_exist_bot(bot_type, id)
         try:
             return bot.send_message(payload=payload)
         except Exception as e:
             self.bot_manager_logger.error(f"Send message failed on bot {id}: {e}")
             raise BotManagerBotException(f"Send message failed: {e}") from e
References bot.BotManager.bot_manager_logger, and bot.BotManager.create_if_not_exist_bot().
start()
def bot.BotManager.start (self, str thread_name = "BotManagerThread", bool daemon = True, ** thread_kwargs)
Definition at line 543 of file bot.py.
     def start(self, thread_name: str = "BotManagerThread", daemon: bool = True, **thread_kwargs):
         try:
             if self.run_thread is None or not self.run_thread.is_alive():
                 self.bot_manager_stop_event.clear()
                 self.run_thread = threading.Thread(
                     target=self.run,
                     name=thread_name,
                     daemon=daemon,
                     **thread_kwargs
                 )
                 self.run_thread.start()
                 self.bot_manager_logger.info(f"Bot Manager Thread '{thread_name}' started")
         except Exception as e:
             self.bot_manager_logger.error(f"Failed to start Bot Manager thread: {e}")
             raise BotManagerStartException(f"Bot Manager start failed: {e}") from e
References bot.BotManager.bot_manager_stop_event, and bot.BotManager.run_thread.
start_bot()
Bot bot.BotManager.start_bot (self, str bot_type, str id, Optional[Callable[[Message], bool]] on_incoming_message = None, Optional[Callable[[Message], bool]] on_outgoing_message = None)
Definition at line 678 of file bot.py.
     def start_bot(self, bot_type: str, id: str,
                   on_incoming_message: Optional[Callable[[Message], bool]] = None,
                   on_outgoing_message: Optional[Callable[[Message], bool]] = None) -> Bot:
         bot = self.create_if_not_exist_bot(bot_type, id)
         if on_incoming_message:
             bot.on_incoming_message = on_incoming_message
         if on_outgoing_message:
             bot.on_outgoing_message = on_outgoing_message
         try:
             bot.start(consumer_out_thread_name=f"BotOutThread-{id}", consumer_in_thread_name=f"BotInThread-{id}", daemon=False)
             return bot
         except Exception as e:
             self.bot_manager_logger.error(f"Failed to start bot {id}: {e}")
             raise BotManagerStartException(f"Bot start failed: {e}") from e
References bot.BotManager.bot_manager_logger, and bot.BotManager.create_if_not_exist_bot().
stop()
def bot.BotManager.stop (self)
Definition at line 569 of file bot.py.
     def stop(self):
         self.bot_manager_logger.info("Stopping Bot Manager...")
         self.bot_manager_stop_event.set()
         if self.run_thread and self.run_thread.is_alive():
             try:
                 self.run_thread.join(timeout=5)
             except Exception as e:
                 self.bot_manager_logger.warning(f"Error stopping run thread: {e}")
                 raise BotManagerStopException(f"Stopping run thread failed: {e}") from e
         self.terminate_bots()
         self.bot_manager_logger.info("Bot Manager terminated")
References bot.BotManager.bot_manager_logger, bot.BotManager.bot_manager_stop_event, and bot.BotManager.run_thread.
Referenced by bot.BotManager.__del__().
stop_bots()
def bot.BotManager.stop_bots (self)
Definition at line 635 of file bot.py.
     def stop_bots(self):
         for bot_type, bots in self.bots.items():
             for id, bot in list(bots.items()):
                 try:
                     bot.stop()
                 except Exception as e:
                     self.bot_manager_logger.warning(
                         f"Error stopping bot {id} of type {bot_type}: {e}"
                     )
         self.bots.clear()
References bot.BotManager.bot_manager_logger.
terminate_and_restart_bot()
Bot bot.BotManager.terminate_and_restart_bot (self, str bot_type, str id)
Definition at line 713 of file bot.py.
     def terminate_and_restart_bot(self, bot_type: str, id: str) -> Bot:
         self.terminate_bot(bot_type, id)
         self.bot_manager_logger.info(f"Restarting bot {id} of type {bot_type}")
         return self.create_bot(bot_type, id)
References bot.BotManager.bot_manager_logger, bot.BotManager.create_bot(), and bot.BotManager.terminate_bot().
Referenced by bot.BotManager.maintain_alive_bots().
terminate_bot()
def bot.BotManager.terminate_bot (self, str bot_type, str id)
Definition at line 718 of file bot.py.
     def terminate_bot(self, bot_type: str, id: str):
         bot = self.get_bot(bot_type, id)
         if bot:
             try:
                 bot.stop()
             except Exception as e:
                 self.bot_manager_logger.warning(f"Error stopping bot {id} of type {bot_type}: {e}")
             del self.bots[bot_type][id]
             self.bot_manager_logger.info(f"Terminated bot {id} of type {bot_type}")
References bot.BotManager.bot_manager_logger, and bot.BotManager.get_bot().
Referenced by bot.BotManager.terminate_and_restart_bot(), and bot.BotManager.terminate_bot_by_instance().
terminate_bot_by_instance()
def bot.BotManager.terminate_bot_by_instance (self, Bot bot)
Definition at line 728 of file bot.py.
     def terminate_bot_by_instance(self, bot: Bot):
         for bot_type, bots in self.bots.items():
             for id, b in list(bots.items()):
                 if b is bot:
                     self.terminate_bot(bot_type, id)
                     return
References bot.BotManager.terminate_bot().
Member Data Documentation
bot_manager_logger
bot.BotManager.bot_manager_logger
Definition at line 536 of file bot.py.
Referenced by bot.BotManager.check_alive_bot(), bot.BotManager.check_alive_bots(), bot.BotManager.create_bot(), bot.BotManager.maintain_alive_bots(), bot.BotManager.receive_message_from_bot(), bot.BotManager.run(), bot.BotManager.send_message_on_bot(), bot.BotManager.start_bot(), bot.BotManager.stop(), bot.BotManager.stop_bots(), bot.BotManager.terminate_and_restart_bot(), and bot.BotManager.terminate_bot().
bot_manager_stop_event
bot.BotManager.bot_manager_stop_event
Definition at line 535 of file bot.py.
Referenced by bot.BotManager.run(), bot.BotManager.start(), and bot.BotManager.stop().
run_cycle_time
bot.BotManager.run_cycle_time
Definition at line 533 of file bot.py.
Referenced by bot.BotManager.run().
run_thread
bot.BotManager.run_thread
Definition at line 547 of file bot.py.
Referenced by bot.BotManager.start(), and bot.BotManager.stop().
The documentation for this class was generated from the following file:
src/bot.py
⬇️ Download 🐙 View on GitHub
© 2025 Giuseppe Pedone — GitHub