.TH "src Directory Reference" 3 "Fri Dec 5 2025" "READMETemplate" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBbot\&.py\fP"
.br
.ti -1c
.RI "file \fBconfigurator\&.py\fP"
.br
.ti -1c
.RI "file \fBdatabase\&.py\fP"
.br
.ti -1c
.RI "file \fBenv\&.py\fP"
.br
.ti -1c
.RI "file \fBexception\&.py\fP"
.br
.ti -1c
.RI "file \fBllm\&.py\fP"
.br
.ti -1c
.RI "file \fBlogger\&.py\fP"
.br
.ti -1c
.RI "file \fBweb_client\&.py\fP"
.br
.ti -1c
.RI "file \fBweb_server\&.py\fP"
.br
.in -1c
