.TH "bot" 3 "Tue Dec 2 2025" "READMETemplate" \" -*- nroff -*-
.ad l
.nh
.SH NAME
bot
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBBot\fP"
.br
.ti -1c
.RI "class \fBBotDeserializationException\fP"
.br
.ti -1c
.RI "class \fBBotException\fP"
.br
.ti -1c
.RI "class \fBBotHealthCheckException\fP"
.br
.ti -1c
.RI "class \fBBotInitializationException\fP"
.br
.ti -1c
.RI "class \fBBotManager\fP"
.br
.ti -1c
.RI "class \fBBotManagerAliveCheckException\fP"
.br
.ti -1c
.RI "class \fBBotManagerBotException\fP"
.br
.ti -1c
.RI "class \fBBotManagerException\fP"
.br
.ti -1c
.RI "class \fBBotManagerStartException\fP"
.br
.ti -1c
.RI "class \fBBotManagerStopException\fP"
.br
.ti -1c
.RI "class \fBBotManagerThreadException\fP"
.br
.ti -1c
.RI "class \fBBotMessageException\fP"
.br
.ti -1c
.RI "class \fBBotMessageQueueEmptyException\fP"
.br
.ti -1c
.RI "class \fBBotMessageQueueException\fP"
.br
.ti -1c
.RI "class \fBBotMessageQueueFullException\fP"
.br
.ti -1c
.RI "class \fBBotMessageQueueLockException\fP"
.br
.ti -1c
.RI "class \fBBotQueuedMessageException\fP"
.br
.ti -1c
.RI "class \fBBotQueuedMessageInvalidException\fP"
.br
.ti -1c
.RI "class \fBBotQueuedMessageResultException\fP"
.br
.ti -1c
.RI "class \fBBotQueueException\fP"
.br
.ti -1c
.RI "class \fBBotReceiveMessageException\fP"
.br
.ti -1c
.RI "class \fBBotSendMessageException\fP"
.br
.ti -1c
.RI "class \fBBotSerializationException\fP"
.br
.ti -1c
.RI "class \fBBotStartException\fP"
.br
.ti -1c
.RI "class \fBBotStartThreadException\fP"
.br
.ti -1c
.RI "class \fBBotStopException\fP"
.br
.ti -1c
.RI "class \fBBotStopThreadException\fP"
.br
.ti -1c
.RI "class \fBBotThreadException\fP"
.br
.ti -1c
.RI "class \fBFacebookBot\fP"
.br
.ti -1c
.RI "class \fBFacebookBotException\fP"
.br
.ti -1c
.RI "class \fBFacebookBotSendMessageException\fP"
.br
.ti -1c
.RI "class \fBHTTPMessage\fP"
.br
.ti -1c
.RI "class \fBHTTPMessageException\fP"
.br
.ti -1c
.RI "class \fBHTTPMessageHeadersException\fP"
.br
.ti -1c
.RI "class \fBHTTPMessageParamsException\fP"
.br
.ti -1c
.RI "class \fBHTTPMessagePayloadException\fP"
.br
.ti -1c
.RI "class \fBIncomingQueuedMessage\fP"
.br
.ti -1c
.RI "class \fBMessage\fP"
.br
.ti -1c
.RI "class \fBOutgoingQueuedMessage\fP"
.br
.ti -1c
.RI "class \fBQueuedMessage\fP"
.br
.ti -1c
.RI "class \fBTelegramBot\fP"
.br
.ti -1c
.RI "class \fBTelegramBotException\fP"
.br
.ti -1c
.RI "class \fBTelegramBotSendMessageException\fP"
.br
.ti -1c
.RI "class \fBWhatsappBot\fP"
.br
.ti -1c
.RI "class \fBWhatsappBotException\fP"
.br
.ti -1c
.RI "class \fBWhatsappBotSendMessageException\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBbot_manager\fP = \fBBotManager\fP(run_cycle_time=environ\&.BOT_MANAGER_RUN_TIMEOUT)"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "bot\&.bot_manager = \fBBotManager\fP(run_cycle_time=environ\&.BOT_MANAGER_RUN_TIMEOUT)"

.PP
Definition at line 764 of file bot\&.py\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for READMETemplate from the source code\&.
