.TH "src/bot.py" 3 "Fri Nov 21 2025" "READMETemplate" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/bot.py
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBbot\&.Bot\fP"
.br
.ti -1c
.RI "class \fBbot\&.BotDeserializationException\fP"
.br
.ti -1c
.RI "class \fBbot\&.BotException\fP"
.br
.ti -1c
.RI "class \fBbot\&.BotHealthCheckException\fP"
.br
.ti -1c
.RI "class \fBbot\&.BotInitializationException\fP"
.br
.ti -1c
.RI "class \fBbot\&.BotManager\fP"
.br
.ti -1c
.RI "class \fBbot\&.BotManagerAliveCheckException\fP"
.br
.ti -1c
.RI "class \fBbot\&.BotManagerBotException\fP"
.br
.ti -1c
.RI "class \fBbot\&.BotManagerException\fP"
.br
.ti -1c
.RI "class \fBbot\&.BotManagerStartException\fP"
.br
.ti -1c
.RI "class \fBbot\&.BotManagerStopException\fP"
.br
.ti -1c
.RI "class \fBbot\&.BotManagerThreadException\fP"
.br
.ti -1c
.RI "class \fBbot\&.BotMessageException\fP"
.br
.ti -1c
.RI "class \fBbot\&.BotMessageQueueEmptyException\fP"
.br
.ti -1c
.RI "class \fBbot\&.BotMessageQueueException\fP"
.br
.ti -1c
.RI "class \fBbot\&.BotMessageQueueFullException\fP"
.br
.ti -1c
.RI "class \fBbot\&.BotMessageQueueLockException\fP"
.br
.ti -1c
.RI "class \fBbot\&.BotQueuedMessageException\fP"
.br
.ti -1c
.RI "class \fBbot\&.BotQueuedMessageInvalidException\fP"
.br
.ti -1c
.RI "class \fBbot\&.BotQueuedMessageResultException\fP"
.br
.ti -1c
.RI "class \fBbot\&.BotQueueException\fP"
.br
.ti -1c
.RI "class \fBbot\&.BotReceiveMessageException\fP"
.br
.ti -1c
.RI "class \fBbot\&.BotSendMessageException\fP"
.br
.ti -1c
.RI "class \fBbot\&.BotSerializationException\fP"
.br
.ti -1c
.RI "class \fBbot\&.BotStartException\fP"
.br
.ti -1c
.RI "class \fBbot\&.BotStartThreadException\fP"
.br
.ti -1c
.RI "class \fBbot\&.BotStopException\fP"
.br
.ti -1c
.RI "class \fBbot\&.BotStopThreadException\fP"
.br
.ti -1c
.RI "class \fBbot\&.BotThreadException\fP"
.br
.ti -1c
.RI "class \fBbot\&.FacebookBot\fP"
.br
.ti -1c
.RI "class \fBbot\&.FacebookBotException\fP"
.br
.ti -1c
.RI "class \fBbot\&.FacebookBotSendMessageException\fP"
.br
.ti -1c
.RI "class \fBbot\&.HTTPMessage\fP"
.br
.ti -1c
.RI "class \fBbot\&.HTTPMessageException\fP"
.br
.ti -1c
.RI "class \fBbot\&.HTTPMessageHeadersException\fP"
.br
.ti -1c
.RI "class \fBbot\&.HTTPMessageParamsException\fP"
.br
.ti -1c
.RI "class \fBbot\&.HTTPMessagePayloadException\fP"
.br
.ti -1c
.RI "class \fBbot\&.IncomingQueuedMessage\fP"
.br
.ti -1c
.RI "class \fBbot\&.Message\fP"
.br
.ti -1c
.RI "class \fBbot\&.OutgoingQueuedMessage\fP"
.br
.ti -1c
.RI "class \fBbot\&.QueuedMessage\fP"
.br
.ti -1c
.RI "class \fBbot\&.TelegramBot\fP"
.br
.ti -1c
.RI "class \fBbot\&.TelegramBotException\fP"
.br
.ti -1c
.RI "class \fBbot\&.TelegramBotSendMessageException\fP"
.br
.ti -1c
.RI "class \fBbot\&.WhatsappBot\fP"
.br
.ti -1c
.RI "class \fBbot\&.WhatsappBotException\fP"
.br
.ti -1c
.RI "class \fBbot\&.WhatsappBotSendMessageException\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBbot\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBbot\&.bot_manager\fP = BotManager(run_cycle_time=environ\&.BOT_MANAGER_RUN_TIMEOUT)"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for READMETemplate from the source code\&.
