.TH "bot.IncomingQueuedMessage" 3 "Wed Dec 3 2025" "READMETemplate" \" -*- nroff -*-
.ad l
.nh
.SH NAME
bot.IncomingQueuedMessage
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBbot\&.QueuedMessage\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fB__init__\fP (self, \fBmessage\fP, int max_store_retries=3)"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 166 of file bot\&.py\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "def bot\&.IncomingQueuedMessage\&.__init__ ( self,  message, int  max_store_retries = \fC3\fP)"

.PP
Reimplemented from \fBbot\&.QueuedMessage\fP\&.
.PP
Definition at line 167 of file bot\&.py\&.
.PP
.nf
167     def __init__(self, message, max_store_retries: int = 3):
168         super()\&.__init__(message, max_store_retries)
169 
170 
.fi


.SH "Author"
.PP 
Generated automatically by Doxygen for READMETemplate from the source code\&.
