.TH "bot.FacebookBotSendMessageException" 3 "Fri Nov 21 2025" "READMETemplate" \" -*- nroff -*-
.ad l
.nh
.SH NAME
bot.FacebookBotSendMessageException
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBbot\&.FacebookBotException\fP\&.
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 120 of file bot\&.py\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for READMETemplate from the source code\&.
