.TH "bot.BotStartThreadException" 3 "Thu Nov 20 2025" "READMETemplate" \" -*- nroff -*-
.ad l
.nh
.SH NAME
bot.BotStartThreadException
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBbot\&.BotThreadException\fP\&.
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 111 of file bot\&.py\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for READMETemplate from the source code\&.
