.TH "bot.HTTPMessage" 3 "Fri Nov 21 2025" "READMETemplate" \" -*- nroff -*-
.ad l
.nh
.SH NAME
bot.HTTPMessage
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fB__init__\fP (self, str \fBpayload\fP, str \fBparams\fP=None, str \fBheaders\fP=None)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBheaders\fP"
.br
.ti -1c
.RI "\fBparams\fP"
.br
.ti -1c
.RI "\fBpayload\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 129 of file bot\&.py\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "def bot\&.HTTPMessage\&.__init__ ( self, str  payload, str  params = \fCNone\fP, str  headers = \fCNone\fP)"

.PP
Definition at line 130 of file bot\&.py\&.
.PP
.nf
130     def __init__(self, payload:str , params: str = None, headers: str = None):
131         self\&.payload = payload
132         self\&.params = params
133         self\&.headers = headers
134 
.fi
.SH "Member Data Documentation"
.PP 
.SS "bot\&.HTTPMessage\&.headers"

.PP
Definition at line 133 of file bot\&.py\&.
.SS "bot\&.HTTPMessage\&.params"

.PP
Definition at line 132 of file bot\&.py\&.
.SS "bot\&.HTTPMessage\&.payload"

.PP
Definition at line 131 of file bot\&.py\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for READMETemplate from the source code\&.
