.TH "bot.BotStartException" 3 "Fri Nov 21 2025" "READMETemplate" \" -*- nroff -*-
.ad l
.nh
.SH NAME
bot.BotStartException
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBbot\&.BotException\fP\&.
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 39 of file bot\&.py\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for READMETemplate from the source code\&.
