.TH "bot.BotException" 3 "Fri Nov 21 2025" "READMETemplate" \" -*- nroff -*-
.ad l
.nh
.SH NAME
bot.BotException
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBexception\&.ChatbotException\fP\&.
.PP
Inherited by \fBbot\&.BotDeserializationException\fP, \fBbot\&.BotHealthCheckException\fP, \fBbot\&.BotInitializationException\fP, \fBbot\&.BotMessageException\fP, \fBbot\&.BotQueueException\fP, \fBbot\&.BotSerializationException\fP, \fBbot\&.BotStartException\fP, \fBbot\&.BotStopException\fP, \fBbot\&.BotThreadException\fP, \fBbot\&.FacebookBotException\fP, \fBbot\&.TelegramBotException\fP, and \fBbot\&.WhatsappBotException\fP\&.
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 33 of file bot\&.py\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for READMETemplate from the source code\&.
