.TH "bot.BotThreadException" 3 "Thu Nov 20 2025" "READMETemplate" \" -*- nroff -*-
.ad l
.nh
.SH NAME
bot.BotThreadException
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBbot\&.BotException\fP\&.
.PP
Inherited by \fBbot\&.BotStartThreadException\fP, and \fBbot\&.BotStopThreadException\fP\&.
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 60 of file bot\&.py\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for READMETemplate from the source code\&.
