.TH "bot.TelegramBotSendMessageException" 3 "Wed Dec 3 2025" "READMETemplate" \" -*- nroff -*-
.ad l
.nh
.SH NAME
bot.TelegramBotSendMessageException
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBbot\&.TelegramBotException\fP\&.
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 117 of file bot\&.py\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for READMETemplate from the source code\&.
