.TH "bot.BotManagerException" 3 "Tue Dec 2 2025" "READMETemplate" \" -*- nroff -*-
.ad l
.nh
.SH NAME
bot.BotManagerException
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBexception\&.ChatbotException\fP\&.
.PP
Inherited by \fBbot\&.BotManagerAliveCheckException\fP, \fBbot\&.BotManagerBotException\fP, \fBbot\&.BotManagerStartException\fP, \fBbot\&.BotManagerStopException\fP, and \fBbot\&.BotManagerThreadException\fP\&.
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 15 of file bot\&.py\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for READMETemplate from the source code\&.
