.TH "configurator" 3 "Thu Dec 4 2025" "READMETemplate" \" -*- nroff -*-
.ad l
.nh
.SH NAME
configurator
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBConfigurationCheckNgrokException\fP"
.br
.ti -1c
.RI "class \fBConfigurationException\fP"
.br
.ti -1c
.RI "class \fBConfigurationExceptionCode\fP"
.br
.ti -1c
.RI "class \fBConfigurationHTTPRequestExcpetion\fP"
.br
.ti -1c
.RI "class \fBConfigurationHTTPRequestMethodExcpetion\fP"
.br
.ti -1c
.RI "class \fBConfigurationHTTPRequestRetryExcpetion\fP"
.br
.ti -1c
.RI "class \fBConfigurationHTTPRequestTimeoutExcpetion\fP"
.br
.ti -1c
.RI "class \fBConfigurationSetTelegramWebhookException\fP"
.br
.ti -1c
.RI "class \fBConfigurationStartNgrokException\fP"
.br
.ti -1c
.RI "class \fBConfigurationStopNgrokException\fP"
.br
.ti -1c
.RI "class \fBConfigurationVerifyNgrokException\fP"
.br
.ti -1c
.RI "class \fBConfigurator\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for READMETemplate from the source code\&.
