.TH "configurator.ConfigurationStartNgrokException" 3 "Fri Nov 21 2025" "READMETemplate" \" -*- nroff -*-
.ad l
.nh
.SH NAME
configurator.ConfigurationStartNgrokException
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBconfigurator\&.ConfigurationException\fP\&.
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 34 of file configurator\&.py\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for READMETemplate from the source code\&.
