.TH "src/configurator.py" 3 "Tue Dec 2 2025" "READMETemplate" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/configurator.py
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBconfigurator\&.ConfigurationCheckNgrokException\fP"
.br
.ti -1c
.RI "class \fBconfigurator\&.ConfigurationException\fP"
.br
.ti -1c
.RI "class \fBconfigurator\&.ConfigurationExceptionCode\fP"
.br
.ti -1c
.RI "class \fBconfigurator\&.ConfigurationHTTPRequestExcpetion\fP"
.br
.ti -1c
.RI "class \fBconfigurator\&.ConfigurationHTTPRequestMethodExcpetion\fP"
.br
.ti -1c
.RI "class \fBconfigurator\&.ConfigurationHTTPRequestRetryExcpetion\fP"
.br
.ti -1c
.RI "class \fBconfigurator\&.ConfigurationHTTPRequestTimeoutExcpetion\fP"
.br
.ti -1c
.RI "class \fBconfigurator\&.ConfigurationSetTelegramWebhookException\fP"
.br
.ti -1c
.RI "class \fBconfigurator\&.ConfigurationStartNgrokException\fP"
.br
.ti -1c
.RI "class \fBconfigurator\&.ConfigurationStopNgrokException\fP"
.br
.ti -1c
.RI "class \fBconfigurator\&.ConfigurationVerifyNgrokException\fP"
.br
.ti -1c
.RI "class \fBconfigurator\&.Configurator\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBconfigurator\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for READMETemplate from the source code\&.
