.TH "configurator.ConfigurationException" 3 "Wed Dec 3 2025" "READMETemplate" \" -*- nroff -*-
.ad l
.nh
.SH NAME
configurator.ConfigurationException
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBexception\&.ChatbotException\fP\&.
.PP
Inherited by \fBconfigurator\&.ConfigurationCheckNgrokException\fP, \fBconfigurator\&.ConfigurationHTTPRequestExcpetion\fP, \fBconfigurator\&.ConfigurationHTTPRequestMethodExcpetion\fP, \fBconfigurator\&.ConfigurationHTTPRequestRetryExcpetion\fP, \fBconfigurator\&.ConfigurationHTTPRequestTimeoutExcpetion\fP, \fBconfigurator\&.ConfigurationSetTelegramWebhookException\fP, \fBconfigurator\&.ConfigurationStartNgrokException\fP, \fBconfigurator\&.ConfigurationStopNgrokException\fP, and \fBconfigurator\&.ConfigurationVerifyNgrokException\fP\&.
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 33 of file configurator\&.py\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for READMETemplate from the source code\&.
