.TH "configurator.ConfigurationExceptionCode" 3 "Fri Nov 21 2025" "READMETemplate" \" -*- nroff -*-
.ad l
.nh
.SH NAME
configurator.ConfigurationExceptionCode
.SH SYNOPSIS
.br
.PP
.PP
Inherits Enum\&.
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "\fBCONFIG_LOGGER_FAILED\fP = auto()"
.br
.ti -1c
.RI "\fBCONFIG_UNEXPECTED_ERROR\fP = auto()"
.br
.ti -1c
.RI "\fBHTTP_METHOD_ERROR\fP = auto()"
.br
.ti -1c
.RI "\fBHTTP_REQUEST_TIMEOUT\fP = auto()"
.br
.ti -1c
.RI "\fBHTTP_TIMEOUT\fP = auto()"
.br
.ti -1c
.RI "\fBNGROK_CHECK_FAILED\fP = auto()"
.br
.ti -1c
.RI "\fBNGROK_NOT_READY\fP = auto()"
.br
.ti -1c
.RI "\fBNGROK_START_FAILED\fP = auto()"
.br
.ti -1c
.RI "\fBNGROK_STOP_FAILED\fP = auto()"
.br
.ti -1c
.RI "\fBNGROK_VERIFY_FAILED\fP = auto()"
.br
.ti -1c
.RI "\fBNO_ERROR\fP = auto()"
.br
.ti -1c
.RI "\fBTELEGRAM_WEBHOOK_HTTP_ERROR\fP = auto()"
.br
.ti -1c
.RI "\fBTELEGRAM_WEBHOOK_METHOD_ERROR\fP = auto()"
.br
.ti -1c
.RI "\fBTELEGRAM_WEBHOOK_UNEXPECTED_ERROR\fP = auto()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 12 of file configurator\&.py\&.
.SH "Member Data Documentation"
.PP 
.SS "configurator\&.ConfigurationExceptionCode\&.CONFIG_LOGGER_FAILED = auto()\fC [static]\fP"

.PP
Definition at line 29 of file configurator\&.py\&.
.SS "configurator\&.ConfigurationExceptionCode\&.CONFIG_UNEXPECTED_ERROR = auto()\fC [static]\fP"

.PP
Definition at line 30 of file configurator\&.py\&.
.SS "configurator\&.ConfigurationExceptionCode\&.HTTP_METHOD_ERROR = auto()\fC [static]\fP"

.PP
Definition at line 15 of file configurator\&.py\&.
.SS "configurator\&.ConfigurationExceptionCode\&.HTTP_REQUEST_TIMEOUT = auto()\fC [static]\fP"

.PP
Definition at line 16 of file configurator\&.py\&.
.SS "configurator\&.ConfigurationExceptionCode\&.HTTP_TIMEOUT = auto()\fC [static]\fP"

.PP
Definition at line 17 of file configurator\&.py\&.
.SS "configurator\&.ConfigurationExceptionCode\&.NGROK_CHECK_FAILED = auto()\fC [static]\fP"

.PP
Definition at line 22 of file configurator\&.py\&.
.SS "configurator\&.ConfigurationExceptionCode\&.NGROK_NOT_READY = auto()\fC [static]\fP"

.PP
Definition at line 20 of file configurator\&.py\&.
.SS "configurator\&.ConfigurationExceptionCode\&.NGROK_START_FAILED = auto()\fC [static]\fP"

.PP
Definition at line 19 of file configurator\&.py\&.
.SS "configurator\&.ConfigurationExceptionCode\&.NGROK_STOP_FAILED = auto()\fC [static]\fP"

.PP
Definition at line 21 of file configurator\&.py\&.
.SS "configurator\&.ConfigurationExceptionCode\&.NGROK_VERIFY_FAILED = auto()\fC [static]\fP"

.PP
Definition at line 23 of file configurator\&.py\&.
.SS "configurator\&.ConfigurationExceptionCode\&.NO_ERROR = auto()\fC [static]\fP"

.PP
Definition at line 13 of file configurator\&.py\&.
.SS "configurator\&.ConfigurationExceptionCode\&.TELEGRAM_WEBHOOK_HTTP_ERROR = auto()\fC [static]\fP"

.PP
Definition at line 25 of file configurator\&.py\&.
.SS "configurator\&.ConfigurationExceptionCode\&.TELEGRAM_WEBHOOK_METHOD_ERROR = auto()\fC [static]\fP"

.PP
Definition at line 26 of file configurator\&.py\&.
.SS "configurator\&.ConfigurationExceptionCode\&.TELEGRAM_WEBHOOK_UNEXPECTED_ERROR = auto()\fC [static]\fP"

.PP
Definition at line 27 of file configurator\&.py\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for READMETemplate from the source code\&.
