.TH "database.Event" 3 "Wed Dec 3 2025" "READMETemplate" \" -*- nroff -*-
.ad l
.nh
.SH NAME
database.Event
.SH SYNOPSIS
.br
.PP
.PP
Inherits Base\&.
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "\fBavailable_sits\fP = Column(Integer)"
.br
.ti -1c
.RI "\fBdate_time\fP = Column(DateTime)"
.br
.ti -1c
.RI "\fBdescription\fP = Column(String)"
.br
.ti -1c
.RI "\fBid\fP = Column(Integer, primary_key=True)"
.br
.ti -1c
.RI "\fBlocation\fP = Column(String)"
.br
.ti -1c
.RI "\fBname\fP = Column(String, unique=True)"
.br
.ti -1c
.RI "\fBtotal_sits\fP = Column(Integer)"
.br
.in -1c
.SS "Static Private Attributes"

.in +1c
.ti -1c
.RI "string \fB__tablename__\fP = 'event'"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 20 of file database\&.py\&.
.SH "Member Data Documentation"
.PP 
.SS "string database\&.Event\&.__tablename__ = 'event'\fC [static]\fP, \fC [private]\fP"

.PP
Definition at line 21 of file database\&.py\&.
.SS "database\&.Event\&.available_sits = Column(Integer)\fC [static]\fP"

.PP
Definition at line 26 of file database\&.py\&.
.SS "database\&.Event\&.date_time = Column(DateTime)\fC [static]\fP"

.PP
Definition at line 28 of file database\&.py\&.
.SS "database\&.Event\&.description = Column(String)\fC [static]\fP"

.PP
Definition at line 24 of file database\&.py\&.
.SS "database\&.Event\&.id = Column(Integer, primary_key=True)\fC [static]\fP"

.PP
Definition at line 22 of file database\&.py\&.
.SS "database\&.Event\&.location = Column(String)\fC [static]\fP"

.PP
Definition at line 25 of file database\&.py\&.
.SS "database\&.Event\&.name = Column(String, unique=True)\fC [static]\fP"

.PP
Definition at line 23 of file database\&.py\&.
.SS "database\&.Event\&.total_sits = Column(Integer)\fC [static]\fP"

.PP
Definition at line 27 of file database\&.py\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for READMETemplate from the source code\&.
