.TH "database.Booking" 3 "Tue Dec 2 2025" "READMETemplate" \" -*- nroff -*-
.ad l
.nh
.SH NAME
database.Booking
.SH SYNOPSIS
.br
.PP
.PP
Inherits Base\&.
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "\fBevent\fP = Column(String)"
.br
.ti -1c
.RI "\fBid\fP = Column(Integer, primary_key=True)"
.br
.ti -1c
.RI "\fBname\fP = Column(String)"
.br
.ti -1c
.RI "\fBnumber_sits\fP = Column(Integer)"
.br
.in -1c
.SS "Static Private Attributes"

.in +1c
.ti -1c
.RI "string \fB__tablename__\fP = 'reservation'"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 9 of file database\&.py\&.
.SH "Member Data Documentation"
.PP 
.SS "string database\&.Booking\&.__tablename__ = 'reservation'\fC [static]\fP, \fC [private]\fP"

.PP
Definition at line 10 of file database\&.py\&.
.SS "database\&.Booking\&.event = Column(String)\fC [static]\fP"

.PP
Definition at line 14 of file database\&.py\&.
.SS "database\&.Booking\&.id = Column(Integer, primary_key=True)\fC [static]\fP"

.PP
Definition at line 11 of file database\&.py\&.
.SS "database\&.Booking\&.name = Column(String)\fC [static]\fP"

.PP
Definition at line 12 of file database\&.py\&.
.SS "database\&.Booking\&.number_sits = Column(Integer)\fC [static]\fP"

.PP
Definition at line 13 of file database\&.py\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for READMETemplate from the source code\&.
