.TH "src/database.py" 3 "Wed Dec 3 2025" "READMETemplate" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/database.py
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBdatabase\&.Booking\fP"
.br
.ti -1c
.RI "class \fBdatabase\&.Database\fP"
.br
.ti -1c
.RI "class \fBdatabase\&.Event\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBdatabase\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBdatabase\&.Base\fP = declarative_base()"
.br
.ti -1c
.RI "\fBdatabase\&.db\fP = Database()"
.br
.ti -1c
.RI "\fBdatabase\&.engine\fP = create_engine('sqlite:///chatbot\&.db')"
.br
.ti -1c
.RI "\fBdatabase\&.Session\fP = sessionmaker(bind=engine)"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for READMETemplate from the source code\&.
