.TH "src/exception.py" 3 "Tue Dec 2 2025" "READMETemplate" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/exception.py
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBexception\&.ChatbotException\fP"
.br
.ti -1c
.RI "class \fBexception\&.ChatbotException\&.ChatbotExceptionCode\fP"
.br
.ti -1c
.RI "class \fBexception\&.ChatbotException\&.ChatbotExceptionSeverity\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBexception\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for READMETemplate from the source code\&.
