.TH "exception.ChatbotException.ChatbotExceptionCode" 3 "Wed Dec 3 2025" "READMETemplate" \" -*- nroff -*-
.ad l
.nh
.SH NAME
exception.ChatbotException.ChatbotExceptionCode
.SH SYNOPSIS
.br
.PP
.PP
Inherits Enum\&.
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "\fBCONFIG_ERROR\fP = auto()"
.br
.ti -1c
.RI "\fBDB_ERROR\fP = auto()"
.br
.ti -1c
.RI "\fBGENERIC_ERROR\fP = auto()"
.br
.ti -1c
.RI "\fBNETWORK_ERROR\fP = auto()"
.br
.ti -1c
.RI "\fBNO_ERROR\fP = auto()"
.br
.ti -1c
.RI "\fBTIMEOUT_ERROR\fP = auto()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 8 of file exception\&.py\&.
.SH "Member Data Documentation"
.PP 
.SS "exception\&.ChatbotException\&.ChatbotExceptionCode\&.CONFIG_ERROR = auto()\fC [static]\fP"

.PP
Definition at line 11 of file exception\&.py\&.
.SS "exception\&.ChatbotException\&.ChatbotExceptionCode\&.DB_ERROR = auto()\fC [static]\fP"

.PP
Definition at line 14 of file exception\&.py\&.
.SS "exception\&.ChatbotException\&.ChatbotExceptionCode\&.GENERIC_ERROR = auto()\fC [static]\fP"

.PP
Definition at line 10 of file exception\&.py\&.
.SS "exception\&.ChatbotException\&.ChatbotExceptionCode\&.NETWORK_ERROR = auto()\fC [static]\fP"

.PP
Definition at line 12 of file exception\&.py\&.
.SS "exception\&.ChatbotException\&.ChatbotExceptionCode\&.NO_ERROR = auto()\fC [static]\fP"

.PP
Definition at line 9 of file exception\&.py\&.
.SS "exception\&.ChatbotException\&.ChatbotExceptionCode\&.TIMEOUT_ERROR = auto()\fC [static]\fP"

.PP
Definition at line 13 of file exception\&.py\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for READMETemplate from the source code\&.
