.TH "src/llm.py" 3 "Thu Nov 20 2025" "READMETemplate" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/llm.py
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBllm\&.AI\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBllm\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "def \fBllm\&.ask_llm\fP (user_id, prompt)"
.br
.ti -1c
.RI "def \fBllm\&.ask_llm2\fP (user_id, prompt)"
.br
.ti -1c
.RI "def \fBllm\&.ask_llm3\fP (user_id, prompt)"
.br
.ti -1c
.RI "def \fBllm\&.info_extraction\fP (user_id, message)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "dictionary \fBllm\&.conversation_history\fP = {}"
.br
.ti -1c
.RI "dictionary \fBllm\&.info_history\fP = {}"
.br
.ti -1c
.RI "int \fBllm\&.MAX_MESSAGES\fP = 10"
.br
.ti -1c
.RI "int \fBllm\&.ONE_DAY_IN_SECONDS\fP = 86400"
.br
.ti -1c
.RI "dictionary \fBllm\&.user_data\fP = {}"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for READMETemplate from the source code\&.
