.TH "llm.AI" 3 "Tue Dec 2 2025" "READMETemplate" \" -*- nroff -*-
.ad l
.nh
.SH NAME
llm.AI
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fB__init__\fP (self)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
Classe per gestire le interazioni con i modelli LLM.

.fi
.PP
 
.PP
Definition at line 171 of file llm\&.py\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "def llm\&.AI\&.__init__ ( self)"

.PP
Definition at line 175 of file llm\&.py\&.
.PP
.nf
175     def __init__(self):
176         pass
.fi


.SH "Author"
.PP 
Generated automatically by Doxygen for READMETemplate from the source code\&.
