.TH "logger.LogWarningOperationException" 3 "Thu Nov 20 2025" "READMETemplate" \" -*- nroff -*-
.ad l
.nh
.SH NAME
logger.LogWarningOperationException
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBlogger\&.LogException\fP\&.
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 23 of file logger\&.py\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for READMETemplate from the source code\&.
