.TH "logger.DefaultLogAttributes" 3 "Fri Dec 5 2025" "READMETemplate" \" -*- nroff -*-
.ad l
.nh
.SH NAME
logger.DefaultLogAttributes
.SH SYNOPSIS
.br
.PP
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "\fBint\fP"
.br
.ti -1c
.RI "\fBstr\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 30 of file logger\&.py\&.
.SH "Member Data Documentation"
.PP 
.SS "logger\&.DefaultLogAttributes\&.int\fC [static]\fP"

.PP
Definition at line 34 of file logger\&.py\&.
.SS "logger\&.DefaultLogAttributes\&.str\fC [static]\fP"

.PP
Definition at line 31 of file logger\&.py\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for READMETemplate from the source code\&.
