.TH "logger" 3 "Wed Dec 3 2025" "READMETemplate" \" -*- nroff -*-
.ad l
.nh
.SH NAME
logger
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBDefaultLogAttributes\fP"
.br
.ti -1c
.RI "class \fBLogConfigurationException\fP"
.br
.ti -1c
.RI "class \fBLogCriticalOperationException\fP"
.br
.ti -1c
.RI "class \fBLogDebugOperationException\fP"
.br
.ti -1c
.RI "class \fBLogErrorOperationException\fP"
.br
.ti -1c
.RI "class \fBLogException\fP"
.br
.ti -1c
.RI "class \fBLogger\fP"
.br
.ti -1c
.RI "class \fBLogInfoOperationException\fP"
.br
.ti -1c
.RI "class \fBLogWarningOperationException\fP"
.br
.ti -1c
.RI "class \fBLogWrongAttributeException\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBencoding\fP"
.br
.ti -1c
.RI "\fBfrozen\fP"
.br
.ti -1c
.RI "\fBmain_logger\fP = \fBLogger\fP(name='Chatbot', enable_file_handler=True, enable_stream_handler=True)"
.br
.ti -1c
.RI "\fBmax_files\fP"
.br
.ti -1c
.RI "\fBmax_size\fP"
.br
.ti -1c
.RI "\fBmin_level\fP"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "logger\&.encoding"

.PP
Definition at line 316 of file logger\&.py\&.
.SS "logger\&.frozen"

.PP
Definition at line 29 of file logger\&.py\&.
.SS "logger\&.main_logger = \fBLogger\fP(name='Chatbot', enable_file_handler=True, enable_stream_handler=True)"

.PP
Definition at line 315 of file logger\&.py\&.
.SS "logger\&.max_files"

.PP
Definition at line 316 of file logger\&.py\&.
.SS "logger\&.max_size"

.PP
Definition at line 316 of file logger\&.py\&.
.SS "logger\&.min_level"

.PP
Definition at line 316 of file logger\&.py\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for READMETemplate from the source code\&.
