.TH "logger.LogException" 3 "Tue Dec 2 2025" "READMETemplate" \" -*- nroff -*-
.ad l
.nh
.SH NAME
logger.LogException
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBexception\&.ChatbotException\fP\&.
.PP
Inherited by \fBlogger\&.LogConfigurationException\fP, \fBlogger\&.LogCriticalOperationException\fP, \fBlogger\&.LogDebugOperationException\fP, \fBlogger\&.LogErrorOperationException\fP, \fBlogger\&.LogInfoOperationException\fP, and \fBlogger\&.LogWarningOperationException\fP\&.
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 19 of file logger\&.py\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for READMETemplate from the source code\&.
