.TH "logger.LogConfigurationException" 3 "Fri Nov 21 2025" "READMETemplate" \" -*- nroff -*-
.ad l
.nh
.SH NAME
logger.LogConfigurationException
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBlogger\&.LogException\fP\&.
.PP
Inherited by \fBlogger\&.LogWrongAttributeException\fP\&.
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 20 of file logger\&.py\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for READMETemplate from the source code\&.
