.TH "md_CONTACT_US" 3 "Tue Dec 2 2025" "READMETemplate" \" -*- nroff -*-
.ad l
.nh
.SH NAME
md_CONTACT_US \- CONTACT_US 

.SH "☎️ Contact us "
.PP
.PP

.br
.PP
You can contact us for anything using \fCGitHub\fP , \fCGmail\fP , \fCSkype\fP , \fCLinkedin\fP  and \fCTelegram \fP at the below addresses, from \fBMonday\fP to \fBSaturday\fP, \fB8\&.30 UTC+1\&.00\fP - \fB18\&.00 UTC+1\&.00\fP:
.PP

.br
.PP
.PP
🗓️ Day Time  \fBMonday\fP 8\&.30 UTC+1\&.00 to 18\&.00 UTC+1\&.00  \fBTuesday\fP 8\&.30 UTC+1\&.00 to 18\&.00 UTC+1\&.00  \fBWednesday\fP 8\&.30 UTC+1\&.00 to 18\&.00 UTC+1\&.00  \fBThursday\fP 8\&.30 UTC+1\&.00 to 18\&.00 UTC+1\&.00  \fBFriday\fP 8\&.30 UTC+1\&.00 to 18\&.00 UTC+1\&.00  \fBSaturday\fP 8\&.30 UTC+1\&.00 to 18\&.00 UTC+1\&.00  
.PP
.PP

.br
 
.br
.PP
We \fBprovide\fP 3 different \fBsupport services\fP supporting:
.PP
.IP "\(bu" 2
👤 \fBCustomers\fP for basic customer issues
.IP "\(bu" 2
🧑‍💼 \fBAdministrators\fP: for administration and managment issues
.IP "\(bu" 2
🧑‍💻 \fBDevelopers\fP for development issues
.PP
.PP

.br
.PP
Supports  Contacts                  👤 \fBCustomer\fP Giuseppe Pedone  \fC\*<\fBUnix69\fP\*> \fP   \fCgiuseppe\&.pedone\&.developer@gmail\&.com\fP giuseppe\&.pedone\&.94 https://www.linkedin.com/in/giupeps94 https://t.me/giupeps  🧑‍💼 \fBAdministrator\fP Giuseppe Pedone  \fC\*<\fBUnix69\fP\*> \fP   \fCgiuseppe\&.pedone\&.developer@gmail\&.com\fP giuseppe\&.pedone\&.94 https://www.linkedin.com/in/giupeps94 https://t.me/giupeps  🧑‍💻 \fBDeveloper\fP Giuseppe Pedone  \fC\*<\fBUnix69\fP\*> \fP   \fCgiuseppe\&.pedone\&.developer@gmail\&.com\fP giuseppe\&.pedone\&.94 https://www.linkedin.com/in/giupeps94 https://t.me/giupeps  
.PP

.br
.PP
💡 \fBBest Practise\fP
.IP "\(bu" 2
\fBBefore contact us\fP, try to use \fB[PROJECT_NAME]\fP tools like \fB[PROJECT_NAME]\fP's guides or related \fB[PROJECT_NAME]\fP's error detection APIs that \fBhelps\fP you to \fBunderstand problems occurred\fP\&.
.IP "\(bu" 2
\fBWhen\fP you \fBuse\fP a support service to ask something, \fBbe clear\fP to express your \fBrequest\fP so that services can help you \fBproperly\fP\&.
.PP
.PP

.br
.PP
1 
