.TH "md_ISSUE_TEMPLATE" 3 "Tue Dec 2 2025" "READMETemplate" \" -*- nroff -*-
.ad l
.nh
.SH NAME
md_ISSUE_TEMPLATE \- ISSUE_TEMPLATE 

.SH "⚠️ Issue Template "
.PP
.PP
Thanks for opening this issue\&. Add a brief description of what this issue is, and how to recreate it\&. Do tag the relevant issue(s) and PR(s) below\&. If required, add some screenshot(s) to showcase the issue\&.
.PP
.IP "\(bu" 2
Relevant Issues : (none)
.IP "\(bu" 2
Relevant PRs : (none)
.IP "\(bu" 2
Type of issue :
.IP "  \(bu" 4
[ ] Installation
.IP "  \(bu" 4
[ ] Font-related
.IP "  \(bu" 4
[ ] Feature request
.IP "  \(bu" 4
[ ] Bug in existing feature
.IP "  \(bu" 4
[ ] Developer mode : Code quality / Tests / Documentation 
.PP

.PP

