.TH "md_LICENSE" 3 "Tue Dec 2 2025" "READMETemplate" \" -*- nroff -*-
.ad l
.nh
.SH NAME
md_LICENSE \- LICENSE 
README Template 
.br
 Copyright (c) 2025 Giuseppe Pedone 
.br
 Email: giuseppe.pedone.developer@gmail.com 
.br
 GitHub: https://github.com/Unix69 
.br
.PP
This work is licensed under the Creative Commons Attribution 4\&.0 International License (CC BY 4\&.0)\&.
.PP
You are free to:
.IP "\(bu" 2
Share — copy and redistribute the material in any medium or format
.IP "\(bu" 2
Adapt — remix, transform, and build upon the material for any purpose, even commercially\&.
.PP
.PP
Under the following terms:
.IP "\(bu" 2
Attribution — You must give appropriate credit to the author (Giuseppe Pedone), provide a link to the original source (https://github.com/Unix69), and indicate if changes were made\&. You may do so in any reasonable manner, but not in any way that suggests the licensor endorses you or your use\&.
.PP
.PP
No additional restrictions — You may not apply legal terms or technological measures that legally restrict others from doing anything the license permits\&.
.PP
THE WORK IS PROVIDED 'AS IS', WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, AND NONINFRINGEMENT\&. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES, OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT, OR OTHERWISE, ARISING FROM, OUT OF, OR IN CONNECTION WITH THE WORK OR THE USE OR OTHER DEALINGS IN THE WORK\&.
.PP
Full license text available at: 
.br
 https://creativecommons.org/licenses/by/4.0/ 
