.TH "md_Version_CHANGELOG" 3 "Fri Dec 5 2025" "READMETemplate" \" -*- nroff -*-
.ad l
.nh
.SH NAME
md_Version_CHANGELOG \- CHANGELOG 

.SH "🔄 Change Log "
.PP
.PP
  
.PP
🏗️  \fCProject\fP  · ⭐  \fCFeatures\fP  · 🎮  \fCUse Cases\fP  · 🏷️  \fCVersions\fP  · 📜  \fCRelease Policy\fP  · 📦  \fCNamespaces\fP  · 🧩  \fCAPIs\fP  · 🐞  \fCBugs\fP  · 🔧  \fCFixes\fP  · 📋  \fCChange Log\fP  · ☎️  \fCContact Us\fP 
.PP

.br

.br
.PP
A \fBChange\fP in **\fBReadme Template\fP** is a modification made on a given \fBdate\fP and \fBtime\fP for a specific **\fBReadme Template\fP Version**, related to \fBFeatures\fP, \fBNamespaces\fP, \fBAPIs\fP, and possibly involving \fBBugs\fP and \fBFixes\fP\&. 
.br
 Logging \fBChanges\fP allows tracking all modifications throughout the **\fBReadme Template\fP** lifecycle\&.
.PP

.br

.br
.PP
.SS "📓 Table of Contents"
.IP "\(bu" 2
\fCTypes of Changes\fP
.IP "\(bu" 2
\fCChange Log\fP
.IP "\(bu" 2
\fCFAQ\fP
.IP "\(bu" 2
\fCContact Us\fP
.IP "\(bu" 2
\fCSee Also\fP
.IP "\(bu" 2
\fCOfficial Links\fP
.PP
.PP

.br

.br
.PP
.SS "🔧 Types of Changes"
🔧 Change 📝 Description  ➕ \fCadd\fP A new component, API, feature, or namespace has been introduced\&.  🛠️ \fCmodify\fP An existing component, API, feature, or namespace has been improved, refactored, or redesigned\&.  ❌ \fCdelete\fP A deprecated component, API, feature, or namespace has been removed safely\&.  🩹 \fCfix\fP A bug or regression has been resolved\&.  
.PP

.br

.br
.PP
.SS "🔄 Change Log"
🔄 Change 🗓️ Date 🆔 ID 🧾 Description 🧩 Versions ⚙️ Features 📦 Namespaces 🔗 APIs  🐞 \fBBug\fP 14/05/2025 03:00 am \fCbug=#122\fP Access a null pointer - [\fCv1\&.1\&.0\fP]()
.br
- [\fCv1\&.2\&.0\fP]() - [\fCdata core features\fP]()
.br
- [\fCmemory management\fP]() - [\fCcore\fP]() - [\fCcore\&.data\fP]()  🔧 \fBFix\fP 14/05/2025 03:00 am \fCfix=#123\fP Added a verify pointer control before access - [\fCv1\&.1\&.0\fP]()
.br
- [\fCv1\&.2\&.0\fP]() - [\fCdata core features\fP]()
.br
- [\fCmemory management\fP]() - [\fCcore\fP]() - [\fCcore\&.data\fP]()  
.PP

.br

.br
.PP
.SH "See Also"
.PP
\fCTable of Contents\fP
.PP

.br
.PP
The following documents are related to this:
.PP
.PD 0
.IP "\(bu" 2
 \fC\fBRelease Policy\fP\fP  file, named \fC\fBRELEASE_POLICY\&.md\fP\fP, contains the \fBRelease Policy\fP standard adopted in \fBREADME Template\fP\&.  
.IP "\(bu" 2
 \fC\fBFeatures\fP\fP  file, named \fC\fBFEATURE\&.md\fP\fP, contains the \fBFeatures\fP of \fBREADME Template\fP\&.  
.IP "\(bu" 2
 \fC\fBAPIs\fP\fP  file, named \fC\fBAPI\&.md\fP\fP, contains the \fBAPIs\fP of \fBREADME Template\fP\&.  
.IP "\(bu" 2
 \fC\fBChange Log\fP\fP  file, named \fC\fBCHANGELOG\&.md\fP\fP, contains the \fBChanges\fP made in \fBREADME Template\fP\&.  
.IP "\(bu" 2
 \fC\fBNamespaces\fP\fP  file, named \fC\fBNAMESPACE\&.md\fP\fP, contains the \fBNamespace\fP architecture of \fBREADME Template\fP\&.  
.IP "\(bu" 2
 \fC\fBBugs\fP\fP  file, named \fC\fBBUG\&.md\fP\fP, contains the \fBBugs\fP identified in \fBREADME Template\fP\&.  
.IP "\(bu" 2
 \fC\fBFixes\fP\fP  file, named \fC\fBFIX\&.md\fP\fP, contains the \fBFixes\fP applied to \fBREADME Template\fP\&.  
.PP
.PP

.br
 
.br
.PP
.SH "FAQ ❓"
.PP
Here you can find the Frequently Asked Questions and Answers\&.
.PP

.br
 
.br
.PP
.SH "Contact us ☎️"
.PP
For \fBmore information\fP on \fBReadme Template\fP \fBcontact us\fP\&.
.PP

.br
 
.br
.PP
.SH "Official Links"
.PP
\fCTable of Contents\fP
.PP
.IP "\(bu" 2
\fCSemVer\fP – A complete guide to \fBSemanting Verioning\fP\&.
.IP "\(bu" 2
\fCDoxygen\fP – \fBDocumentation generator\fP for source code\&.
.IP "\(bu" 2
\fCGitHub\fP – \fBHosting\fP and \fBcollaboration platform\fP for \fBGit\fP repositories\&.
.IP "\(bu" 2
\fCGit\fP – \fBVersion control\fP system to manage source code\&.
.IP "\(bu" 2
\fCGNU Make\fP – \fBBuild automation tool\fP to compile projects\&.
.PP
.PP

.br
 
.br
 
