.TH "md_Version_CHANGELOG" 3 "Fri Nov 21 2025" "READMETemplate" \" -*- nroff -*-
.ad l
.nh
.SH NAME
md_Version_CHANGELOG \- CHANGELOG 

.SH "🔄 Change Log "
.PP
.PP
  
.PP
🏗️ \fBProject\fP  ·  ⭐ \fBFeatures\fP  ·  🎮 \fBUse Cases\fP  ·  🏷️ \fBVersions\fP  ·  📜 \fBRelease Policy\fP  ·  📦 \fBNamespaces\fP  ·  🧩 \fBAPIs\fP  ·  🐞 \fBBugs\fP  ·  🔧 \fBFixes\fP  ·  📋 \fBChange Log\fP  ·  ☎️ \fBContact Us\fP 
.br

.br
.PP
A \fBChange\fP in \fB[PROJECT_NAME]\fP is a modification made on a given \fBdate\fP and \fBtime\fP for a specific \fB[PROJECT_NAME] Version\fP, related to \fBFeatures\fP, \fBNamespaces\fP, \fBAPIs\fP, and possibly involving \fBBugs\fP and \fBFixes\fP\&. 
.br
 Logging \fBChanges\fP allows tracking all modifications throughout the \fB[PROJECT_NAME]\fP lifecycle\&.
.PP

.br

.br
.PP
.SS "📓 Table of Contents"
.IP "\(bu" 2
\fCTypes of Changes\fP
.IP "\(bu" 2
\fCChange Log\fP
.IP "\(bu" 2
\fCFAQ\fP
.IP "\(bu" 2
\fCContact Us\fP
.IP "\(bu" 2
\fCSee Also\fP
.IP "\(bu" 2
\fCOfficial Links\fP
.PP
.PP

.br

.br
.SS "🔧 Types of Changes"
🔧 Change 📝 Description  ➕ \fCadd\fP A new component, API, feature, or namespace has been introduced\&.  🛠️ \fCmodify\fP An existing component, API, feature, or namespace has been improved, refactored, or redesigned\&.  ❌ \fCdelete\fP A deprecated component, API, feature, or namespace has been removed safely\&.  🩹 \fCfix\fP A bug or regression has been resolved\&.  
.PP

.br

.br
.SS "🔄 Change Log"
🔄 Change 🗓️ Date 🆔 ID 🧾 Description 🧩 Versions ⚙️ Features 📦 Namespaces 🔗 APIs  🐞 \fBBug\fP 14/05/2025 03:00 am \fCbug=#122\fP Access a null pointer - [\fCv1\&.1\&.0\fP]()
.br
- [\fCv1\&.2\&.0\fP]() - [\fCdata core features\fP]()
.br
- [\fCmemory management\fP]() - [\fCcore\fP]() - [\fCcore\&.data\fP]()  🔧 \fBFix\fP 14/05/2025 03:00 am \fCfix=#123\fP Added a verify pointer control before access - [\fCv1\&.1\&.0\fP]()
.br
- [\fCv1\&.2\&.0\fP]() - [\fCdata core features\fP]()
.br
- [\fCmemory management\fP]() - [\fCcore\fP]() - [\fCcore\&.data\fP]()  
.PP

.br

.br
.PP
.SH "See Also"
.PP
\fCTable of Contents\fP
.PP

.br
.PP
The following documents are related to this:
.PP
.PD 0
.IP "\(bu" 2
.IP "  \(bu" 4
\fBProject\fP file, named \fC\fBPROJECT\&.md\fP\fP, contains the \fI\fBProject Description\fP\fP of \fBREADME Template\fP\&.  
.PP

.IP "\(bu" 2
.IP "  \(bu" 4
\fBUse Cases\fP file, named \fC\fBUSECASES\&.md\fP\fP, shows the \fI\fBUse Cases\fP\fP of \fBREADME Template\fP\&.  
.PP

.IP "\(bu" 2
.IP "  \(bu" 4
\fBActors\fP file, named \fC\fBACTORS\&.md\fP\fP, explains the types of \fI\fBActors\fP\fP in \fBREADME Template\fP\&.  
.PP

.IP "\(bu" 2
.IP "  \(bu" 4
\fBRoles\fP file, named \fC\fBROLES\&.md\fP\fP, describes the \fI\fBRoles\fP\fP of the \fI\fBActors\fP\fP in \fBREADME Template\fP\&.  
.PP

.IP "\(bu" 2
.IP "  \(bu" 4
\fBAdministrator Guide\fP file, named \fC\fBADMINISTRATOR_GUIDE\&.md\fP\fP, explains to \fI\fBAdministrators\fP\fP how to manage \fBREADME Template\fP\&.  
.PP

.IP "\(bu" 2
.IP "  \(bu" 4
\fBUser Guide\fP file, named \fC\fBUSER_GUIDE\&.md\fP\fP, explains to \fI\fBUsers\fP\fP how to use \fBREADME Template\fP\&.  
.PP

.IP "\(bu" 2
.IP "  \(bu" 4
\fBDeveloper Guide\fP file, named \fC\fBDEVELOPMENT_GUIDE\&.md\fP\fP, explains to \fI\fBDevelopers\fP\fP how to develop \fBREADME Template\fP\&.  
.PP

.IP "\(bu" 2
.IP "  \(bu" 4
\fBVersions\fP file, named \fC\fBVERSION\&.md\fP\fP, shows and explains each \fI\fBVersion\fP\fP of \fBREADME Template\fP\&.  
.PP

.IP "\(bu" 2
.IP "  \(bu" 4
\fBRelease Policy\fP file, named \fC\fBRELEASE_POLICY\&.md\fP\fP, contains the \fI\fBRelease Policy\fP\fP standard adopted in \fBREADME Template\fP\&.  
.PP

.IP "\(bu" 2
.IP "  \(bu" 4
\fBFeatures\fP file, named \fC\fBFEATURE\&.md\fP\fP, contains the \fI\fBFeatures\fP\fP of \fBREADME Template\fP\&.  
.PP

.IP "\(bu" 2
.IP "  \(bu" 4
\fBAPIs\fP file, named \fC\fBAPI\&.md\fP\fP, contains the \fI\fBAPIs\fP\fP of \fBREADME Template\fP\&.  
.PP

.IP "\(bu" 2
.IP "  \(bu" 4
\fBChange Log\fP file, named \fC\fBCHANGELOG\&.md\fP\fP, contains the \fI\fBChanges\fP\fP made in \fBREADME Template\fP\&.  
.PP

.IP "\(bu" 2
.IP "  \(bu" 4
\fBNamespaces\fP file, named \fC\fBNAMESPACE\&.md\fP\fP, contains the \fI\fBNamespace\fP\fP architecture of \fBREADME Template\fP\&.  
.PP

.IP "\(bu" 2
.IP "  \(bu" 4
\fBBugs\fP file, named \fC\fBBUG\&.md\fP\fP, contains the \fI\fBBugs\fP\fP identified in \fBREADME Template\fP\&.  
.PP

.IP "\(bu" 2
.IP "  \(bu" 4
\fBFixes\fP file, named \fC\fBFIX\&.md\fP\fP, contains the \fI\fBFixes\fP\fP applied to \fBREADME Template\fP\&.  
.PP

.PP

.br
.PP
.SH "FAQ ❓"
.PP
Here you can find the Frequently Asked Questions and Answers\&.
.PP

.br
 
.br
.PP
.SH "Contact us ☎️"
.PP
For \fBmore information\fP on [PROJECT_NAME] \fBcontact us\fP\&.
.PP
.SH "Official Links"
.PP
\fCTable of Contents\fP
.PP
.IP "\(bu" 2
\fCSemVer\fP – A complete guide to \fBSemanting Verioning\fP\&.
.IP "\(bu" 2
\fCDoxygen\fP – \fBDocumentation generator\fP for source code\&.
.IP "\(bu" 2
\fCGitHub\fP – \fBHosting\fP and \fBcollaboration platform\fP for \fBGit\fP repositories\&.
.IP "\(bu" 2
\fCGit\fP – \fBVersion control\fP system to manage source code\&.
.IP "\(bu" 2
\fCGNU Make\fP – \fBBuild automation tool\fP to compile projects\&.
.PP
.PP

.br
 
.br
 
