.TH "web_client.WebClient" 3 "Tue Dec 2 2025" "READMETemplate" \" -*- nroff -*-
.ad l
.nh
.SH NAME
web_client.WebClient
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fB__init__\fP (self, app)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
Classe per gestire le interazioni con il client web.

.fi
.PP
 
.PP
Definition at line 382 of file web_client\&.py\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "def web_client\&.WebClient\&.__init__ ( self,  app)"

.PP
Definition at line 386 of file web_client\&.py\&.
.PP
.nf
386     def __init__(self, app):
387         pass
.fi


.SH "Author"
.PP 
Generated automatically by Doxygen for READMETemplate from the source code\&.
