.TH "web_server.WebAppRunException" 3 "Wed Dec 3 2025" "READMETemplate" \" -*- nroff -*-
.ad l
.nh
.SH NAME
web_server.WebAppRunException
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBweb_server\&.WebAppException\fP\&.
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 37 of file web_server\&.py\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for READMETemplate from the source code\&.
