.TH "src/web_client.py" 3 "Fri Nov 21 2025" "READMETemplate" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/web_client.py
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBweb_client\&.WebClient\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBweb_client\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "string \fBweb_client\&.html_events\fP"
.br
.ti -1c
.RI "string \fBweb_client\&.html_home\fP"
.br
.ti -1c
.RI "string \fBweb_client\&.html_reservation\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for READMETemplate from the source code\&.
