.TH "web_client" 3 "Thu Nov 20 2025" "READMETemplate" \" -*- nroff -*-
.ad l
.nh
.SH NAME
web_client
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBWebClient\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "string \fBhtml_events\fP"
.br
.ti -1c
.RI "string \fBhtml_home\fP"
.br
.ti -1c
.RI "string \fBhtml_reservation\fP"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "string web_client\&.html_events"

.PP
Definition at line 254 of file web_client\&.py\&.
.SS "string web_client\&.html_home"

.PP
Definition at line 1 of file web_client\&.py\&.
.SS "string web_client\&.html_reservation"

.PP
Definition at line 62 of file web_client\&.py\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for READMETemplate from the source code\&.
