.TH "web_server.WebAppException" 3 "Thu Dec 4 2025" "READMETemplate" \" -*- nroff -*-
.ad l
.nh
.SH NAME
web_server.WebAppException
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBexception\&.ChatbotException\fP\&.
.PP
Inherited by \fBweb_server\&.WebAppConfigurationException\fP, \fBweb_server\&.WebAppRunException\fP, \fBweb_server\&.WebAppStartException\fP, \fBweb_server\&.WebAppStopException\fP, and \fBweb_server\&.WebAppVerifyException\fP\&.
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 34 of file web_server\&.py\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for READMETemplate from the source code\&.
