.TH "src/web_server.py" 3 "Fri Dec 5 2025" "READMETemplate" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/web_server.py
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBweb_server\&.WebApp\fP"
.br
.ti -1c
.RI "class \fBweb_server\&.WebAppConfigurationException\fP"
.br
.ti -1c
.RI "class \fBweb_server\&.WebAppException\fP"
.br
.ti -1c
.RI "class \fBweb_server\&.WebAppRunException\fP"
.br
.ti -1c
.RI "class \fBweb_server\&.WebAppStartException\fP"
.br
.ti -1c
.RI "class \fBweb_server\&.WebAppStopException\fP"
.br
.ti -1c
.RI "class \fBweb_server\&.WebAppVerifyException\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBweb_server\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBweb_server\&.app\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for READMETemplate from the source code\&.
